### ISSUE TITLE
npm: Vulnerability in googleapis

### ISSUE THREAD

**Issue by m-mohr** [google/earthengine-api#101]
I'm using @google/earthengine (JavaScript) in version 0.1.185. When installing / auditing via npm it reports:

```
c:\Dev\openeo-earthengine-driver>npm audit

                       === npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  High            Improper Authorization

  Package         googleapis

  Patched in      >=38.0.0

  Dependency of   @google/earthengine

  Path            @google/earthengine > googleapis

  More info       https://npmjs.com/advisories/791

found 1 vulnerabilities (1 high) in 877972 scanned packages
  1 vulnerabilities require manual review. See the full report for details.
```

I guess you should use googleapis >= 38.0.0 in package.json.

**Comment by donmccurdy** [comment]
The underlying issue (https://github.com/googleapis/google-api-nodejs-client/issues/1594) appears to be a pretty narrow one – if you're using `googleapis` with multiple different credentials at the same time, on the same server, those credentials may become swapped. The Earth Engine JS client can be initialized with only a single private key at a time, so for this situation to arise you'd need to have installed and used a vulnerable version of `googleapis` independently in your Node.js application.

The risk in this situation does not appear high, as the NPM audit claims, but I agree we should bump the dependencies when possible.

**Comment by donmccurdy** [comment]
Fixed in 0.1.186.

**Comment by m-mohr** [comment]
@donmccurdy Thanks for the fix. Unfortunately, since upgrading to 0.1.186 I get the following error:

```
c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:14528
  var jwtClient = new googleapis.auth.JWT(privateKey.client_email, null, privateKey.private_key, scopes, null);
                                      ^

TypeError: Cannot read property 'JWT' of undefined
    at Object.ee.data.authenticateViaPrivateKey (c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:14528:39)
    at new Server (c:\Dev\openeo-earthengine-driver\server.js:47:11)
    at Object.<anonymous> (c:\Dev\openeo-earthengine-driver\server.js:239:17)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
```

Downgrading to 0.1.185 solves the issue, but produces the vulnerability warning again. Do we need to change any code or so for 0.1.186?

**Comment by gino-m** [comment]
Ran into the same issue myself. Filed #103 to track.
