### ISSUE TITLE
Sentinel 2 Surface Reflectance delay

### ISSUE THREAD

**Issue by joaquinperaza** [google/earthengine-api#102]
Anyone knows why there is a 3 weeks delay in most parts of the world in the "COPERNICUS/S2_SR" dataset compared to raw dataset?

**Comment by simonff** [comment]
We download the L2 data from the ONDA mirror, which adds a delay. I'll look into whether we can start getting L2 from scihib directly (scihub is quite overloaded, so we are not always able to get all the new data from it in time)

**Comment by joaquinperaza** [comment]
Any news?, actually ONDA made new images available after 2 weeks in my ROI, but still waiting earthengine to ingest them, scihub was available 72hs after taken, adding that source would be great

**Comment by simonff** [comment]
We are downloading L2 directly from scihub now, and the products should be available in EE about a day after they appears on scihub.

**Comment by joaquinperaza** [comment]
I still having problems in this region system:index: 20190713T135121_20190713T135754_T21HVE
That is the last SR image in my ROI, level 1 have 13 images after that one. I don't know if it's a bug or something ONDA and SciHub both have newer images available.

**Comment by simonff** [comment]
What are some example product IDs that scihub has and EE doesn't?

**Comment by joaquinperaza** [comment]
S2B_MSIL2A_20190718T135119_N0213_R024_T21HVE_20190718T193615
S2A_MSIL2A_20190723T135121_N0213_R024_T21HVE_20190723T172146
S2B_MSIL2A_20190728T135119_N0213_R024_T21HVE_20190728T161250
S2A_MSIL2A_20190802T135121_N0213_R024_T21HVE_20190802T162149
S2B_MSIL2A_20190807T135119_N0213_R024_T21HVE_20190807T192345

S2A_MSIL2A_20190812T135121_N0213_R024_T21HVE_20190812T194611
S2A_MSIL2A_20190812T135121_N0213_R024_T21JVF_20190812T194611

**Comment by simonff** [comment]
Thank you. Some of them are waiting for ingestion. I'll scale up the ingestion pipeline to increase its throughput.

**Comment by joaquinperaza** [comment]
Hi, I am expecting again delays in SR images particularly S2B_MSIL2A_20191006T135119_N0213_R024_T21HVE_20191006T192735
and 
S2A_MSIL2A_20191011T135121_N0213_R024_T21HVE_20191011T162232

**Comment by szaprzal** [comment]
As you said, Sentinel-2 L2A images are included from ONDAS, but how obtain Sentinel-2 L1C data in Earth Engine? It is the same repository or it is directly obtained from ESA-Hub?

**Comment by simonff** [comment]
Currently all S2 images, L1 and L2, are being obtained from ESA's scihub directly

**Comment by szaprzal** [comment]
-@simonoff Thank you. In this case, why L2 data in GEE have a delay of 7-8 days for each orbit? (in opposite to L1C data which was upload in only 2 days after image adquisition). I know the fact of ESA´s Hub offer L2 images next day after adquisition, in some cases at least 2 days.

**Comment by joaquinperaza** [comment]
Still waiting L1C images with delays of more than a week from ingestion.
S2B_MSIL1C_20200602T135119_N0209_R024_T21HVE_20200602T184617
S2A_MSIL1C_20200528T135121_N0209_R024_T21HVE_20200528T153122

**Comment by simonff** [comment]
How did you determine they are missing? Please see https://developers.google.com/earth-engine/help_missing_images

S2B_MSIL1C_20200602T135119_N0209_R024_T21HVE_20200602T184617 was ingested on Jun 3 as COPERNICUS/S2/20200602T135119_20200602T140008_T21HVE

S2A_MSIL1C_20200528T135121_N0209_R024_T21HVE_20200528T153122 was ingested on May 29 as COPERNICUS/S2/20200528T135121_20200528T135118_T21HVE

**Comment by joaquinperaza** [comment]
Sorry, my mistake, i am having problems using L2A (Surface Reflectance) with those dates, images: 
S2A_MSIL2A_20200528T135121_N0214_R024_T21HVE_20200528T162030
S2B_MSIL2A_20200602T135119_N0214_R024_T21HVE_20200602T192359

last image available in EE:
S2A_MSIL2A_20200518T135121_N0214_R024_T21HVE_20200518T161839

**Comment by simonff** [comment]
Thank you, we have a download pipeline bug. I'm fixing it now and will make the alert for this problem more visible.

**Comment by joaquinperaza** [comment]
Any news?, still with problems

**Comment by simonff** [comment]
We are about half caught up with the backlog.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
