### ISSUE TITLE
Python: "Undefined variable from import: Reducer"

### ISSUE THREAD

**Issue by rockClimber88** [google/earthengine-api#107]
```python
import ee
ee.Initialize()
```

```python
# Population density
dataset = ee.ImageCollection("CIESIN/GPWv411/GPW_Population_Density").first()
raster = dataset.select('population_density')

#Locations to extract pop. density
locations = ee.Geometry.MultiPoint(
  [
  77.968, 21.94,  
  83.231, 21.215, 
  76.804, 19.732
  ]);

popDensLocs = raster.reduceRegions(locations, ee.Reducer.toList(), 1000)  # 1000 is the scale in meters
popDensLocs = popDensLocs.aggregate_array("list")
popDensLocs = ee.List(popDensLocs).join(",")
print("Population densities:", popDensLocs)
```

The above python script to calculate population density at a number of locations didn't work. There's error message on my Eclipse IDE on line #21 "Undefined variable from import: Reducer" and it didn't print out the population densities for the 3 locations. Below is the JavaScript code for Google Earth Engine IDE and it worked printing out the population densities. I've spent quite a bit of time trying to make it work but couldn't really figure it out. 

```javascript
var dataset = ee.ImageCollection("CIESIN/GPWv411/GPW_Population_Density").first();
var raster = dataset.select('population_density');
var raster_vis = {
  "max": 1000.0, 
  "palette": [
    "ffffe7", 
    "FFc869", 
    "ffac1d", 
    "e17735", 
    "f2552c", 
    "9f0c21"
  ], 
  "min": 200.0
};
Map.setCenter(79.1, 19.81, 7);
Map.addLayer(raster, raster_vis, 'population_density');

// Locations to extract pop. density
var locations = ee.Geometry.MultiPoint(
  [
  77.968, 21.94,  
  83.231, 21.215, 
  76.804, 19.732
  ]);

Map.addLayer(locations, {color: 'blue'}, 'Locations');

var popDensLocs = raster.reduceRegions(locations, ee.Reducer.toList(), 1000)  // 1000 is the scale in meters
popDensLocs = popDensLocs.aggregate_array("list")
popDensLocs = ee.List(popDensLocs).join(",")
print("Population densities:", popDensLocs)
```

![image](https://user-images.githubusercontent.com/55462751/65076293-8c3c9300-d94d-11e9-946a-96f61dd935e3.png)

**Comment by donmccurdy** [comment]
Just to clarify — the Javascript code you shared is working, but the Python example is not?

This sounds a bit like https://github.com/google/earthengine-api/issues/57 – could you confirm that `ee.Initialize()` was called, and the versions of Python and the EE API you're using?

**Comment by rockClimber88** [comment]
Hi Don,

Correct.

I've looked at #57 . In that case the poster said it worked even though he got an error message. Yes I called ee.initialize() as you could see in the second line of the python script. I use Eclipse with Python plugin PyDev and Python 3.7.4. I installed the latest earth engine api; not sure what the version number is. Do I have to run it from a conda environment?

**Comment by fitoprincipe** [comment]
I tested it, and works fine using Python 3.7.3 and earthengine-api version 0.1.197

**Comment by rockClimber88** [comment]
What's your development environment?

**Comment by fitoprincipe** [comment]
I use 

- linux mint 18
- virtualenv
- jupyter

**Comment by rockClimber88** [comment]
So it looks like I have to use either Jupyter or Conda

**Comment by tylere** [comment]
Although Jupyter or Conda are convenient, the are not required. You should also be able to install:

1.  using pip: `pip install earthengine-api` or 
2. installing directly from https://github.com/google/earthengine-api/tree/master/python using the setup.py file. You man need to manually install the dependencies if you use this method.

If you have problems with the above, please share detailed instructions on how you are installing the Earth Engine Python API package.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
