### ISSUE TITLE
Does Canny edge detection only have a unit as "pixel"?

### ISSUE THREAD

**Issue by M-Harrington** [google/earthengine-api#122]
I'm trying to build a landcover classifier and using the canny edge detection as well as a number of kernels.  I noticed in the kernels you can choose to specify units as "pixel" and "meters" with the general warning that choosing pixel will cause the output to be scaled by the zoom.  

Because I'm building a classifier, any sort of scaling like this is not desirable and preferably I need everything using the underlying raster (Landsat 5) at the highest resolution. Luckily the kernels have this option built in, but from what I can guess, it looks like `ee.Algorithms.CannyEdgeDetector` only uses the pixel-scaling option.  Is this a correct understanding? 

As a linked issue, outputting the classification layer slows down significantly when zoomed in (because of increasing number of pixels to be classified on). Because of the difference in zooms my classifier sometimes gives completely different predictions depending on current zoom which is not desirable behavior. Is there a better way to prevent the classifier from changing output depending on the zoom other than simply setting the zoom to 12 (~38m per pixel) and then re-running the algorithm?

**Comment by M-Harrington** [comment]
I tried answering the last question with the `reproject()` command and setting {scale: 1}. I thought this might be a more direct way of getting around the scaling issue.  However, after using the command and trying to view the accuracy and confusion matrix of my classifier I get the error: `Output of image computation is too large (293.9 MiB > 80.0 MiB)`.  I've collected roughly 8000 pixels for training from the underlying image with about 12 bands, so I wouldn't think that this is the source of the error alone.  Likewise trying to decrease the number of pixels trained on by subsampling doesn't help either, so there must be a different error.

**Comment by ucalyptus** [comment]
Can anyone tell where is the codebase located for ee.Algorithms ? cc: @M-Harrington @michaelfdewitt

**Comment by M-Harrington** [comment]
@ucalyptus I'm actually not sure.  I've tried looking for it without success, maybe it's not part of the public repository? That's part of why I wasn't sure originally if canny was calculating based on pixel scaling only from the documentation.

**Comment by ucalyptus** [comment]
@M-Harrington yeah  u r right. I wanted to understand ee.Model and propose some changes to it

**Comment by tylere** [comment]
Note that in order to be more responsive to bug reports and feature requests, we are transitioning from using GitHub Issues to Google Issue Tracker, which better integrates with the Earth Engine team's software development workflow. Please see the [Get Help](https://developers.google.com/earth-engine/help) page of the Earth Engine documentation for an overview of the recommended communication channels.

Cheers,
Tyler

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
