### ISSUE TITLE
ee.Initialize() and An error [Errno 2]

### ISSUE THREAD

**Issue by HNoorazar** [google/earthengine-api#123]
I can go to http://code.earthengine.google.com/ and do stuff in there. But I want to use the Python notebooks, https://colab.research.google.com/, When I do `ee.initialize()` I get the following error.

I do authenticate and then refresh the Colab Notebook, but the error occurs again! 

The stackoverflow suggests to open a service account, however, this page: https://developers.google.com/earth-engine/service_account#register-the-service-account-to-use-earth-engine, says: You do not need a service account to use the Earth Engine Python API. I am in a loop!

Any help is appreciated.

FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/ee/data.py in get_persistent_credentials()
    217   try:
--> 218     tokens = json.load(open(oauth.get_credentials_path()))
    219     refresh_token = tokens['refresh_token']

FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/earthengine/credentials'

During handling of the above exception, another exception occurred:

EEException                               Traceback (most recent call last)
2 frames
/usr/local/lib/python3.6/dist-packages/ee/data.py in get_persistent_credentials()
    227   except IOError:
    228     raise ee_exception.EEException(
--> 229         'Please authorize access to your Earth Engine account by '
    230         'running\n\nearthengine authenticate\n\nin your command line, and then '
    231         'retry.')

EEException: Please authorize access to your Earth Engine account by running

earthengine authenticate

in your command line, and then retry.

**Comment by AmazonCc** [comment]
I  also want to use python ,but I meet the same problem, did you solve this ?

**Comment by HNoorazar** [comment]
No. Gave up on Python. 
1. Every time you have to authenticate.
2. new packages are developed/updated for Java Script. (who knows when those will be available for Python).
3. Tutorials for Java are abundant, but scarce for Python.

**Comment by rogeralmengor** [comment]
I don't know if the situation has improved, but I have to go to JavaScript anytime I see the Python API for GEE breaking apart.
