### ISSUE TITLE
HTTP: 404 error when using ee.initialize() for OAuth

### ISSUE THREAD

**Issue by anishatandon** [google/earthengine-api#124]
Hello! I'm pretty new to using earth engine, but am trying to use OAuth. My code is attached below, but I keep getting the error:
Server returned HTTP code: 404 
`push../node_modules/@google/earthengine/build/browser.js.module$contents$ee$apiclient_apiclient.send | @ | browser.js:24966
  | push../node_modules/@google/earthengine/build/browser.js.ee.data.getAlgorithms | @ | browser.js:31569
  | push../node_modules/@google/earthengine/build/browser.js.ee.ApiFunction.initialize | @ | browser.js:33049
  | push../node_modules/@google/earthengine/build/browser.js.ee.initialize | @ | browser.js:35595
  | ./src/components/earthEngine.js
`
code: 
`var ee = require('@google/earthengine');

// Initialize client library and run analysis.
var initialize = function() {
    ee.initialize(null, null, function() {
      // ... run analysis ...
    }, function(e) {
      console.error('Initialization error: ' + e);
    });
  };
  
// Authenticate using an OAuth pop-up.
ee.data.authenticateViaOauth( YOUR_CLIENT_ID, initialize, function(e) {
  console.error('Authentication error: ' + e);
}, null, function() {
  ee.data.authenticateViaPopup(initialize);
});

// Authenticate 
ee.data.authenticateViaOauth( YOUR_CLIENT_ID);
ee.initialize();`

I know I am using an id for an account that has been approved to use earth engine, since i am able to use the online console.

Any help is appreciated!

**Comment by maxwell-oroark** [comment]
+1

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
