### ISSUE TITLE
Download Url issue by using python api for GEE

### ISSUE THREAD

**Issue by 16charan08** [google/earthengine-api#128]
My code is below someone please try to help solve the issue.
---------------------------------------------------------------------
 woreda = ee.FeatureCollection("users/ramcharankankanala/Modified")

 collections = ee.ImageCollection('NASA/FLDAS/NOAH01/C/GL/M/V001') \
   .filterDate('2009-05', '2010-05') \
   .filterBounds(woreda) .select(['Tair_f_tavg','Qair_f_tavg','Rainf_f_tavg',
             'SoilMoi00_10cm_tavg','SoilMoi10_40cm_tavg','SoilMoi100_200cm_tavg',
             'SoilMoi40_100cm_tavg'])

 Map = folium.Map(location=[-180, -90], zoom_start=4)
 Map.setOptions('ROADMAP')
 Map.setCenter(41, 10, 5.9)

def tempfilter(image):
    
    tf_c = image.select('Tair_f_tavg').subtract(273.15).rename('tf_c');
    rf_mm = image.select('Rainf_f_tavg').multiply(86400).rename('rf_mm');
 
    return image.addBands(tf_c.float()).addBands(rf_mm);  

x = collections.map(tempfilter)
  
mean = x.reduce(ee.Reducer.mean())

def get_url(image, scale, region):
    """ Parameters:
        name (str): name of the created folder
        image (ee.image.Image): image to export
        scale (int): resolution of export in meters (e.g: 30 for Landsat)
        region (list): region of interest

    Returns:
        path (str)
     """
    path = image.getDownloadURL({
        'scale': scale,
        'region':(region)
        })

    webbrowser.open_new_tab(path)
    return path

get_url( mean.select('tf_c_mean').first(mean) , 30 , woreda)

---------------------------------------------------------
Error:- EEException: Image.clipToBoundsAndScale, argument 'geometry': Invalid type. Expected: Geometry. Actual: FeatureCollection.
---------------------------------------------------------
Please, someone, get back to me.

**Comment by tylere** [comment]
In order to be more responsive to bug reports and feature requests, we are transitioning from using GitHub Issues to Google Issue Tracker, which better integrates with the Earth Engine team's software development workflow. Please see the [Get Help](https://developers.google.com/earth-engine/help) page of the Earth Engine documentation for details on how to browse and submit issues to Issue Tracker.
