### ISSUE TITLE
problem initializing the earth engine python

### ISSUE THREAD

**Issue by ianakoto** [google/earthengine-api#13]
I get this response when i try to setup the earth engine call locally and initialize it. I followed the earth engine python installation tutorial but its given me the following error

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    print(ee.Image(1))
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\site-packages\ee\computedobject.py", line 32, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\site-packages\ee\image.py", line 52, in __init__
    self.initialize()
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\site-packages\ee\image.py", line 98, in initialize
    apifunction.ApiFunction.importApi(cls, 'Image', 'Image')
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\site-packages\ee\apifunction.py", line 180, in importApi
    cls.initialize()
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\site-packages\ee\apifunction.py", line 151, in initialize
    signatures = data.getAlgorithms()
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\site-packages\ee\data.py", line 410, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\site-packages\ee\data.py", line 738, in send_
    response, content = send_with_backoff()
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\site-packages\ee\data.py", line 728, in send_with_backoff
    headers=headers)
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\site-packages\httplib2-0.10.3-py3.5.egg\httplib2\__init__.py", line 1322, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\site-packages\httplib2-0.10.3-py3.5.egg\httplib2\__init__.py", line 1072, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\site-packages\httplib2-0.10.3-py3.5.egg\httplib2\__init__.py", line 995, in _conn_request
    conn.connect()
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1253, in connect
    super().connect()
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\socket.py", line 712, in create_connection
    raise err
  File "C:\Users\IAN CECIL AKOTO\AppData\Local\Programs\Python\Python35\lib\socket.py", line 703, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by tylere** [comment]
The [Python Installation](https://developers.google.com/earth-engine/python_install) instructions have been updated since you posted. Are you still encountering this issue?

**Comment by ali1100** [comment]
@tylere 
I have the similar issue with setting up python API except at the end line I get this:
EEException: Server returned HTTP code: 403

**Comment by calebjuma27** [comment]
try to trouble shoot your network's "incoming connections". i was experiencing something similar and doing that solved the issue

**Comment by ucalyptus** [comment]
@tylere maybe it's solved?

**Comment by carlo0604** [comment]
@calebjuma27 what do you mean with "trouble shoot your network's incoming connections"?

**Comment by calebjuma27** [comment]
@carlo0604 using the control panel. Network and internet option-Control Panel\All Control Panel Items\Troubleshooting\Network and Internet-and selecting incoming connections.

**Comment by Mohammadreza20** [comment]
When I signed up for Google Earth Engine then import ee and run ee.Authenticate() got token and imported it in jupyter notebook after that run ee.Initialize() then get HTTP 403 error, please help me I don't know what do I doing!


This is Error: HttpError: <HttpError 403 when requesting https://earthengine.googleapis.com/$discovery/rest?version=v1alpha&prettyPrint=false returned "Forbidden">

**Comment by hafez-ahmad** [comment]
import os
import ee
ee.Initialize()
---------------------------------------------------------------------------
UnknownApiNameOrVersion                   Traceback (most recent call last)
<ipython-input-2-99e03d56abd3> in <module>
----> 1 ee.Initialize()

~\miniconda3\lib\site-packages\ee\__init__.py in Initialize(credentials, opt_url, cloud_api_key, http_transport, project)
    114   if credentials == 'persistent':
    115     credentials = data.get_persistent_credentials()
--> 116   data.initialize(
    117       credentials=credentials,
    118       api_base_url=(opt_url + '/api' if opt_url else None),

~\miniconda3\lib\site-packages\ee\data.py in initialize(credentials, api_base_url, tile_base_url, cloud_api_base_url, cloud_api_key, project, http_transport)
    197   _http_transport = http_transport
    198 
--> 199   _install_cloud_api_resource()
    200 
    201   if project is not None:

~\miniconda3\lib\site-packages\ee\data.py in _install_cloud_api_resource()
    264 
    265   timeout = (_deadline_ms / 1000.0) or None
--> 266   _cloud_api_resource = _cloud_api_utils.build_cloud_resource(
    267       _cloud_api_base_url,
    268       credentials=_credentials,

~\miniconda3\lib\site-packages\ee\_cloud_api_utils.py in build_cloud_resource(api_base_url, api_key, credentials, timeout, headers_supplier, response_inspector, http_transport, raw)
    141   else:
    142     alt_model = None
--> 143   resource = discovery.build(
    144       'earthengine',
    145       VERSION,

~\miniconda3\lib\site-packages\googleapiclient\_helpers.py in positional_wrapper(*args, **kwargs)
    132                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    133                     logger.warning(message)
--> 134             return wrapped(*args, **kwargs)
    135 
    136         return positional_wrapper

~\miniconda3\lib\site-packages\googleapiclient\discovery.py in build(serviceName, version, http, discoveryServiceUrl, developerKey, model, requestBuilder, credentials, cache_discovery, cache, client_options, adc_cert_path, adc_key_path, num_retries, static_discovery)
    271 
    272         try:
--> 273             content = _retrieve_discovery_doc(
    274                 requested_url,
    275                 discovery_http,

~\miniconda3\lib\site-packages\googleapiclient\discovery.py in _retrieve_discovery_doc(url, http, cache_discovery, serviceName, version, cache, developerKey, num_retries, static_discovery)
    385             return content
    386         else:
--> 387             raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
    388 
    389     actual_url = url

UnknownApiNameOrVersion: name: earthengine  version: v1alpha

**Comment by Mohammadreza20** [comment]
@hafez-ahmad 
reinstall with pip or anaconda or upgrade it, then: 

```python
import ee
ee.Authenticate()
ee.Initialize()
```

**Comment by simonff** [comment]
Please update to the most recent client that fixes all the issues.

**Comment by EdenGeology** [comment]
ee.Initialize()

AttributeError                            Traceback (most recent call last)
      1 ee.Authenticate()
----> 2 ee.Initialize()

~\anaconda3\envs\geo_env\lib\site-packages\ee\__init__.py in Initialize(credentials, opt_url, cloud_api_key, http_transport, project)
    114   if credentials == 'persistent':
    115     credentials = data.get_persistent_credentials()
--> 116   data.initialize(
    117       credentials=credentials,
    118       api_base_url=(opt_url + '/api' if opt_url else None),

~\anaconda3\envs\geo_env\lib\site-packages\ee\data.py in initialize(credentials, api_base_url, tile_base_url, cloud_api_base_url, cloud_api_key, project, http_transport)
    201   _http_transport = http_transport
    202 
--> 203   _install_cloud_api_resource()
    204 
    205   if project is not None:

~\anaconda3\envs\geo_env\lib\site-packages\ee\data.py in _install_cloud_api_resource()
    260 
    261   timeout = (_deadline_ms / 1000.0) or None
--> 262   _cloud_api_resource = _cloud_api_utils.build_cloud_resource(
    263       _cloud_api_base_url,
    264       credentials=_credentials,

~\anaconda3\envs\geo_env\lib\site-packages\ee\_cloud_api_utils.py in build_cloud_resource(api_base_url, api_key, credentials, timeout, headers_supplier, response_inspector, http_transport, raw)
    132       .format(api_base_url, VERSION))
    133   if http_transport is None:
--> 134     http_transport = httplib2.Http(timeout=timeout)
    135   if credentials is not None:
    136     http_transport = AuthorizedHttp(credentials, http=http_transport)

~\anaconda3\envs\geo_env\lib\site-packages\httplib2shim\__init__.py in __init__(self, cache, timeout, proxy_info, ca_certs, disable_ssl_certificate_validation, pool)
    115 
    116         if not pool:
--> 117             pool = self._make_pool(proxy_info=proxy_info)
    118 
    119         self.pool = pool

~\anaconda3\envs\geo_env\lib\site-packages\httplib2shim\__init__.py in _default_make_pool(http, proxy_info)
     43     cert_reqs = 'CERT_REQUIRED' if http.ca_certs and not ssl_disabled else None
     44 
---> 45     if isinstance(proxy_info, collections.Callable):
     46         proxy_info = proxy_info()
     47     if proxy_info:

AttributeError: module 'collections' has no attribute 'Callable'

**Comment by Mohammadreza20** [comment]
Please check that your proxy or VPN aren't connected or 
Address : Control Panel\Network and Internet\Network and Sharing Center\Internet Options\connections\ LAN settings .
Should be disable

Reinstall with pip or anaconda or upgrade it, then:


```python
import ee
ee.Authenticate()
ee.Initialize()
```

**Comment by Mohammadreza20** [comment]
> ee.Initialize()
> 
> AttributeError Traceback (most recent call last) 1 ee.Authenticate() ----> 2 ee.Initialize()
> 
> ~\anaconda3\envs\geo_env\lib\site-packages\ee__init__.py in Initialize(credentials, opt_url, cloud_api_key, http_transport, project) 114 if credentials == 'persistent': 115 credentials = data.get_persistent_credentials() --> 116 data.initialize( 117 credentials=credentials, 118 api_base_url=(opt_url + '/api' if opt_url else None),
> 
> ~\anaconda3\envs\geo_env\lib\site-packages\ee\data.py in initialize(credentials, api_base_url, tile_base_url, cloud_api_base_url, cloud_api_key, project, http_transport) 201 _http_transport = http_transport 202 --> 203 _install_cloud_api_resource() 204 205 if project is not None:
> 
> ~\anaconda3\envs\geo_env\lib\site-packages\ee\data.py in _install_cloud_api_resource() 260 261 timeout = (_deadline_ms / 1000.0) or None --> 262 _cloud_api_resource = _cloud_api_utils.build_cloud_resource( 263 _cloud_api_base_url, 264 credentials=_credentials,
> 
> ~\anaconda3\envs\geo_env\lib\site-packages\ee_cloud_api_utils.py in build_cloud_resource(api_base_url, api_key, credentials, timeout, headers_supplier, response_inspector, http_transport, raw) 132 .format(api_base_url, VERSION)) 133 if http_transport is None: --> 134 http_transport = httplib2.Http(timeout=timeout) 135 if credentials is not None: 136 http_transport = AuthorizedHttp(credentials, http=http_transport)
> 
> ~\anaconda3\envs\geo_env\lib\site-packages\httplib2shim__init__.py in **init**(self, cache, timeout, proxy_info, ca_certs, disable_ssl_certificate_validation, pool) 115 116 if not pool: --> 117 pool = self._make_pool(proxy_info=proxy_info) 118 119 self.pool = pool
> 
> ~\anaconda3\envs\geo_env\lib\site-packages\httplib2shim__init__.py in _default_make_pool(http, proxy_info) 43 cert_reqs = 'CERT_REQUIRED' if http.ca_certs and not ssl_disabled else None 44 ---> 45 if isinstance(proxy_info, collections.Callable): 46 proxy_info = proxy_info() 47 if proxy_info:
> 
> AttributeError: module 'collections' has no attribute 'Callable'

@EdenGeology

Please check that your proxy or VPN aren't connected or 
Address : Control Panel\Network and Internet\Network and Sharing Center\Internet Options\connections\ LAN settings .
Should be disable

Reinstall with pip or anaconda or upgrade it, then:


```python
import ee
ee.Authenticate()
ee.Initialize()
```

**Comment by EdenGeology** [comment]
Hi there Mohammad Reza

 

I have checked that all proxy and VPN are disconnected. But I still get the same error trying to initialize Earthengine

 

Please can you advise to what other issues I may be running into? 

 

Thank you 

 

Michael Eden Ray

B.Sc (Hons) | M.Sc (Geology) – University of the Witwatersand | Cand. Sci. Nat. 

Data Analyst – Exploration & Mining Geology

Tel: +27 (0) 79 882 5451

Email:  ***@***.***> ***@***.***

Website:  <http://www.earthlabtech.com/> www.earthlabtech.com



Confidential:  This email and its attachments may contain confidential and privileged information.  If you are not the intended recipient, you are not authorized to retain, copy, or distribute the email message or its attachments.  If you received this email in error, please notify the sender immediately. E&OE.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
