### ISSUE TITLE
`ee.Initialize` in example notebooks causes `403 Permission denied` on Google Colab

### ISSUE THREAD

**Issue by prhbrt** [google/earthengine-api#136]
**I wasn't able to post any issues to the Google Issue tracker.**

Both these example scripts result in an `403 Permission denied`

* [EE API](https://colab.research.google.com/github/google/earthengine-api/blob/master/python/examples/ipynb/ee-api-colab-setup.ipynb)
* [UNET regression](https://colab.research.google.com/github/google/earthengine-api/blob/master/python/examples/ipynb/UNET_regression_demo.ipynb)

At the first cell:

    # Import, authenticate and initialize the Earth Engine library.
    import ee
    ee.Authenticate()
    ee.Initialize()

This error occurs due to `ee.Initialize()`:

    To authorize access needed by Earth Engine, open the following URL in a web browser and follow the instructions. If the web browser does not start automatically, please manually browse the URL below.

        .... url ...

    The authorization workflow will generate a code, which you should paste in the box below. 
    Enter verification code: ... code ...

    Successfully saved authorization token.
    ---------------------------------------------------------------------------
    HttpError                                 Traceback (most recent call last)
    /usr/local/lib/python3.6/dist-packages/ee/data.py in _execute_cloud_call(call, num_retries)
        337   try:
    --> 338     return call.execute(num_retries=num_retries)
        339   except googleapiclient.errors.HttpError as e:

    6 frames
    /usr/local/lib/python3.6/dist-packages/googleapiclient/_helpers.py in positional_wrapper(*args, **kwargs)
        133                     logger.warning(message)
    --> 134             return wrapped(*args, **kwargs)
        135 

    /usr/local/lib/python3.6/dist-packages/googleapiclient/http.py in execute(self, http, num_retries)
        897         if resp.status >= 300:
    --> 898             raise HttpError(resp, content, uri=self.uri)
        899         return self.postproc(resp, content)

    HttpError: <HttpError 403 when requesting https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/algorithms?prettyPrint=false&alt=json returned "Permission denied.">

    During handling of the above exception, another exception occurred:

    EEException                               Traceback (most recent call last)
    <ipython-input-10-9f6ffe164bd0> in <module>()
        1 import ee
        2 ee.Authenticate()
    ----> 3 ee.Initialize()

    /usr/local/lib/python3.6/dist-packages/ee/__init__.py in Initialize(credentials, opt_url, use_cloud_api, cloud_api_key, http_transport, project)
        123       http_transport=http_transport)
        124   # Initialize the dynamically loaded functions on the objects that want them.
    --> 125   ApiFunction.initialize()
        126   Element.initialize()
        127   Image.initialize()

    /usr/local/lib/python3.6/dist-packages/ee/apifunction.py in initialize(cls)
        152     """Initializes the list of signatures from the Earth Engine front-end."""
        153     if not cls._api:
    --> 154       signatures = data.getAlgorithms()
        155       api = {}
        156       for name, sig in signatures.items():

    /usr/local/lib/python3.6/dist-packages/ee/data.py in getAlgorithms()
    1041       call = _cloud_api_resource.projects().algorithms().list(
    1042           project=_get_projects_path(), prettyPrint=False)
    -> 1043     return _cloud_api_utils.convert_algorithms(_execute_cloud_call(call))
    1044   return send_('/algorithms', {}, 'GET')
    1045 

    /usr/local/lib/python3.6/dist-packages/ee/data.py in _execute_cloud_call(call, num_retries)
        338     return call.execute(num_retries=num_retries)
        339   except googleapiclient.errors.HttpError as e:
    --> 340     raise _translate_cloud_exception(e)
        341 
        342 

    EEException: Permission denied.

I tried to look for a GEE service in the google cloud console to enable it, but couldn't find one.

Do you need more then just a Google account to use GEE?

**Comment by tylere** [comment]
What prevented you from posting an issue to the Google IssueTracker?

**Comment by PAGiesting** [comment]
Maybe the fact that the front page of Google Issue Tracker says, "Issue Tracker is a tool used internally at Google to track bugs and feature requests during product development." https://developers.google.com/issue-tracker

I have the same problem as the OP, as you might expect.

**Comment by PAGiesting** [comment]
Oh, of course. I had opened this link amid the blizzard of links from the front page for Google Earth Engine and forgot to follow through on signing up. https://signup.earthengine.google.com

Now everything is fine.

**Comment by ahnuljz** [comment]
+1

**Comment by ahnuljz** [comment]
G:\Paper\npm\earthengine-api\demos\server-auth-nodejs>node server
Authenticating Earth Engine API using private key...
Authentication successful.
Error: Not signed up for Earth Engine. Visit https://earthengine.google.com/signup/
    at module$contents$ee$apiclient_Call.callback (G:\Paper\npm\node_modules\@google\earthengine\build\main.js:21451:62)
    at G:\Paper\npm\node_modules\@google\earthengine\build\main.js:15221:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Please make sure you have created a service account and have been approved.
Visit https://developers.google.com/earth-engine/service_account#how-do-i-create-a-service-account to learn more.

**Comment by Vorlajuck** [comment]
i got this message while running GEE code on ArcGIS Pro
To authorize access needed by Earth Engine, open the following URL in a web browser and follow the instructions. If the web browser does not start automatically, please manually browse the URL below.

    https://code.earthengine.google.com/client-auth?scopes=https%3A//www.googleapis.com/auth/earthengine%20https%3A//www.googleapis.com/auth/devstorage.full_control&request_id=dg1WpdXA1L0QLjznsClR6tKacvmBN_LiWEvOWiY75FI&tc=u4Fu_SS2ZnZFqpKWQjd2CthYkgKoqxq_sUjvNUt1dCc&cc=hHXZxBEI7zya-3-y6FkM4AuQaeptuPYd1X5FJEuKnOQ

The authorization workflow will generate a code, which you should paste in the box below.
Enter verification code:

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
