### ISSUE TITLE
TypeError: unsupported operand type(s) for >>: 'tuple' and 'file' (mapclient.py)

### ISSUE THREAD

**Issue by iamlukesky** [google/earthengine-api#14]
Running any of the python examples I get errors like this:

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/ee/mapclient.py", line 446, in run
    print() >> sys.stderr, e
TypeError: unsupported operand type(s) for >>: 'tuple' and 'file'

```

```
Ubuntu: 16.10
Python: 2.7.12+
google-api-python-client: 1.6.2
```

Most recently it happened trying to run the clipped_composite.py example.
Is this caused by an error on my side or is this a bug?

**Comment by tylere** [comment]
Can you provide more information about your environment (operating system, distribution, version, etc.)? What version of the Earth Engine Python API are you using when you encounter these errors?

**Comment by iamlukesky** [comment]
Completely slipped my mind to include that, I've now updated my post.

**Comment by max99x** [comment]
Looks like a bad application of 2to3 (the script that updates Python 2 code to Python 3). The `print() >> sys.stderr, e` line in `mapclient.py` should be `print >> sys.stderr, e` in Python 2 or `print(e, file=sys.stderr)` in Python 3. Of course, that will just fix that print, which itself is printing an error (probably an auth failure), so it won't fix all your issues, but it should let you get one step further.

**Comment by husatoyan** [comment]
I had the same problem with you. Have you ever solved the problem yet?

**Comment by tylere** [comment]
We have not been actively maintaining the mapclient object, because it depends on Tk, a graphical user interface toolkit, which behaves differently on different machines.
