### ISSUE TITLE
Error: Not signed up for Earth Engine -------from the server-auth-nodejs demo

### ISSUE THREAD

**Issue by ahnuljz** [google/earthengine-api#140]
### **server-auth-nodejs/server.js**

`const ee = require("@google/earthengine");
const express = require("express");
const privateKey = require("./.private-key.json");
const port = process.env.PORT || 3000;

// Define endpoint at /mapid.
const app = express().get("/mapid", (_, response) => {
  const srtm = ee.Image("CGIAR/SRTM90_V4");
  const slope = ee.Terrain.slope(srtm);
  slope.getMap({ min: 0, max: 60 }, ({ mapid }) => response.send(mapid));
});

console.log("Authenticating Earth Engine API using private key...");
ee.data.authenticateViaPrivateKey(
  privateKey,
  () => {
    console.log("Authentication successful.");
    ee.initialize(
      null,
      null,
      () => {
        console.log("Earth Engine client library initialized.");
        app.listen(port);
        console.log(`Listening on port ${port}`);
      },
      (err) => {
        console.log(err);
        console.log(
          `Please make sure you have created a service account and have been approved.
Visit https://developers.google.com/earth-engine/service_account#how-do-i-create-a-service-account to learn more.`
        );
      }
    );
  },
  (err) => {
    console.log(err);
  }
);`

### **output：**

`G:\Paper\npm\earthengine-api\demos\server-auth-nodejs>node server
Authenticating Earth Engine API using private key...
Authentication successful.
Error: Not signed up for Earth Engine. Visit https://earthengine.google.com/signup/
    at module$contents$ee$apiclient_Call.callback (G:\Paper\npm\node_modules\@google\earthengine\build\main.js:21451:62)
    at G:\Paper\npm\node_modules\@google\earthengine\build\main.js:15221:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Please make sure you have created a service account and have been approved.
Visit https://developers.google.com/earth-engine/service_account#how-do-i-create-a-service-account to learn more.`

### **and， I find some clues on Google Cloud Platform about Google Earth Engine API's log:**

method: google.earthengine.v1alpha.EarthEngine.ListAlgorithms,  code: 403, ratio: 100%

**Comment by ahnuljz** [comment]
node -v   
v14.13.0

npm -v
6.14.8

google/earthengine
@google/earthengine@0.1.238

the error blocked me for a whole day, help plz!

**Comment by ahnuljz** [comment]
so,  I did it again and it worked，thanks for the awareson platform.

by the way, I can give the newer some help if I konw.

**Comment by kaditya97** [comment]
How you solved it, I am using python API and facing the same problem

**Comment by kumpinar** [comment]
Hi @ahnuljz 
I am getting same issue, how did you solve it?

**Comment by kumpinar** [comment]
I found my mistake

https://developers.google.com/earth-engine/guides/service_account

![image](https://user-images.githubusercontent.com/760904/100390239-bbb25980-3040-11eb-96cf-4e7dd275490f.png)

**Comment by jsonkao** [comment]
Thank you @kumpinar !

**Comment by rohithinnomick** [comment]
I was Signed up for google Earth engine and i was placed my privatekey in specified place in my code but shows an error "Not Signed up for Earth Engine" Please Help me

**Comment by ramiqcom** [comment]
@rohithinnomick you need to register your service account too! try https://signup.earthengine.google.com/#!/service_accounts

**Comment by allythe** [comment]
THANK YOU!!!
