### ISSUE TITLE
Parameter object is required for some coordinates

### ISSUE THREAD

**Issue by vasanththangavel** [google/earthengine-api#141]
```
dem=ee.Image("CGIAR/SRTM90_V4")
point_coords=ee.Geometry.Point(11.2485,78.3387)
elev = dem.sample(point_coords,30).first().get('elevation').getInfo()
```

issue:
HttpError: <HttpError 400 when requesting https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/value:compute?prettyPrint=false&alt=json returned "Element.get: Parameter 'object' is required.">

During handling of the above exception, another exception occurred:

EEException                               Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/ee/data.py in _execute_cloud_call(call, num_retries)
    345     return call.execute(num_retries=num_retries)
    346   except googleapiclient.errors.HttpError as e:
--> 347     raise _translate_cloud_exception(e)
    348 
    349 

EEException: Element.get: Parameter 'object' is required.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
