### ISSUE TITLE
NOTICE: Do not create new issues here.

### ISSUE THREAD

**Issue by Jose-Augusto-C-M** [google/earthengine-api#149]
In order to be more responsive to bug reports and feature requests, we are transitioning from using GitHub Issues to Google Issue Tracker, which better integrates with the Earth Engine team's software development workflow. Please see the [Get Help](https://developers.google.com/earth-engine/help) page of the Earth Engine documentation for details on how to browse and submit issues to Issue Tracker.

 Hello, i´m suffering from a very slow "ee.Initialize()" comand runtime. What is more strange is that some days earlier I ee.initialize was very fast, and all of sudden, it stopped working properly, is there a known issue about that? What i need to inform?

**Comment by schwehr** [comment]
See the get help link for where to discuss issues like the one you describe.
