### ISSUE TITLE
Update region parameter for model deployment

### ISSUE THREAD

**Issue by JonasMedu** [google/earthengine-api#152]
**Problem**:
 - Models deployed on the AI platform can only be reach at [earth-engine](https://code.earthengine.google.com/) it the _--region_ parameter is set to global
 
**Solution**:
Specify the _--region_  parameter at Model- and Version creation

**Comment by JonasMedu** [comment]
The issue is already discussed here:
https://groups.google.com/g/google-earth-engine-developers/c/ZrLtK_RNecU

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
