### ISSUE TITLE
When running "ee.Initialize" an error occurs - SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by caio-valente14** [google/earthengine-api#154]
I've been having a real hard time trying to figure out how can I solve this issue with Python (it only happen on company's computer, on my persional it doesn't happen).

While I was trying to work with Google Earth Engine API for Python, when I run "ee.Initialize()", which is going to initialize the service, it returns some SSL certificate verification error:

```
ssl.SSLError: (SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)'),)
```

I've already looked for this in other questions posted at Stackoverflow and I've found this one (the second answer is the one I need to execute because I cannot remove the verification of certificates since I'm having this issue on my company's computer - on my own PC it's running everything fine): <br>
https://stackoverflow.com/questions/33699577/conda-update-failed-ssl-error-ssl-certificate-verify-failed-certificate-ver

The problem is that, since I'm a beginner in programming, I didn't understand very well what I am supposed to do because of two reasons: I couldn't find the `"pathToYourFile".crt` (I've found some certificates searching ".crt", but I'm not sure which file the person is talking about) and I couldn't find the path to `.condarc`. 

I saw people in this linked question who commented the answer asking how to do so (but no one answered them) and, apparently, one who had succeded with this procedure.

So how can I find this file the person commented in his answer and how can I find the `.condarc` file?

Or is that another way of doing this validation with certificates without deactivating the certification?

**Comment by tylere** [comment]
In order to be more responsive to bug reports and feature requests, we are transitioning from using GitHub Issues to Google Issue Tracker, which better integrates with the Earth Engine team's software development workflow. Please see the [Get Help](https://developers.google.com/earth-engine/help) page of the Earth Engine documentation for details on how to browse and submit issues to Issue Tracker.
