### ISSUE TITLE
earth engine intialization showing error UnknownApiNameOrVersion: name: earthengine  version: v1alpha

### ISSUE THREAD

**Issue by pawansingh1610** [google/earthengine-api#158]
In order to be more responsive to bug reports and feature requests, we are transitioning from using GitHub Issues to Google Issue Tracker, which better integrates with the Earth Engine team's software development workflow. Please see the [Get Help](https://developers.google.com/earth-engine/help) page of the Earth Engine documentation for details on how to browse and submit issues to Issue Tracker.

---------------------------------------------------------------------------
UnknownApiNameOrVersion                   Traceback (most recent call last)
<ipython-input-5-99e03d56abd3> in <module>
----> 1 ee.Initialize()

~\Anaconda3\envs\earthengine\lib\site-packages\ee\__init__.py in Initialize(credentials, opt_url, cloud_api_key, http_transport, project)
    121       cloud_api_key=cloud_api_key,
    122       project=project,
--> 123       http_transport=http_transport)
    124   # Initialize the dynamically loaded functions on the objects that want them.
    125   ApiFunction.initialize()

~\Anaconda3\envs\earthengine\lib\site-packages\ee\data.py in initialize(credentials, api_base_url, tile_base_url, cloud_api_base_url, cloud_api_key, project, http_transport)
    197   _http_transport = http_transport
    198 
--> 199   _install_cloud_api_resource()
    200 
    201   if project is not None:

~\Anaconda3\envs\earthengine\lib\site-packages\ee\data.py in _install_cloud_api_resource()
    271       headers_supplier=_make_request_headers,
    272       response_inspector=_handle_profiling_response,
--> 273       http_transport=_http_transport)
    274 
    275   _cloud_api_resource_raw = _cloud_api_utils.build_cloud_resource(

~\Anaconda3\envs\earthengine\lib\site-packages\ee\_cloud_api_utils.py in build_cloud_resource(api_base_url, api_key, credentials, timeout, headers_supplier, response_inspector, http_transport, raw)
    149       requestBuilder=request_builder,
    150       model=alt_model,
--> 151       cache_discovery=False)
    152 
    153   return resource

~\Anaconda3\envs\earthengine\lib\site-packages\googleapiclient\_helpers.py in positional_wrapper(*args, **kwargs)
    132                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    133                     logger.warning(message)
--> 134             return wrapped(*args, **kwargs)
    135 
    136         return positional_wrapper

~\Anaconda3\envs\earthengine\lib\site-packages\googleapiclient\discovery.py in build(serviceName, version, http, discoveryServiceUrl, developerKey, model, requestBuilder, credentials, cache_discovery, cache, client_options, adc_cert_path, adc_key_path, num_retries, static_discovery)
    280                 developerKey,
    281                 num_retries=num_retries,
--> 282                 static_discovery=static_discovery,
    283             )
    284             service = build_from_document(

~\Anaconda3\envs\earthengine\lib\site-packages\googleapiclient\discovery.py in _retrieve_discovery_doc(url, http, cache_discovery, serviceName, version, cache, developerKey, num_retries, static_discovery)
    385             return content
    386         else:
--> 387             raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
    388 
    389     actual_url = url

UnknownApiNameOrVersion: name: earthengine  version: v1alpha

**Comment by rhensen** [comment]
I also am dealing with this error!

**Comment by gaozitianhaha** [comment]
Same error here!

**Comment by gaozitianhaha** [comment]
I found downgrade the **google-api-python-client** package useful
I use conda to downgrade the package

First change to "rgee" env : conda activate C:\Users\....\AppData\Local\r-miniconda\envs\rgee. You can find all the exisiting env by typing "conda info --envs" in the anaconda Prompt.

Then use this line to downgrade the client package:(rgee) conda install -c conda-forge google-api-python-client==1.12.8
and restart R and it works

**Comment by pawansingh1610** [comment]
@gaozitianhaha  thank you for the suggestion it worked!

**Comment by pawansingh1610** [comment]
But what can be the problem with the new version

**Comment by simonff** [comment]
Apologies for the problem. We plan to fix it as soon as possible this week.

**Comment by rhensen** [comment]
@simonff has the issue been fixed ? I am still getting the same error.

**Comment by simonff** [comment]
Not yet, but we are testing the fixes. Use an older google-api-python-client as a temporary workaround.

**Comment by vsmartins** [comment]
Hey,
I had this issue. The solution is the downgrade of client

pip install --upgrade google-api-python-client==1.12.8

It works for me.

**Comment by simonff** [comment]
The issue is fixed, please install the latest earthengine-api package 0.1.256.
