### ISSUE TITLE
in earthengine python script Image.addBands() showing unknown source image error

### ISSUE THREAD

**Issue by pawansingh1610** [google/earthengine-api#159]
HttpError                                 Traceback (most recent call last)
~\anaconda3\envs\ee\lib\site-packages\ee\data.py in _execute_cloud_call(call, num_retries)
    333   try:
--> 334     return call.execute(num_retries=num_retries)
    335   except googleapiclient.errors.HttpError as e:

~\anaconda3\envs\ee\lib\site-packages\googleapiclient\_helpers.py in positional_wrapper(*args, **kwargs)
    133                     logger.warning(message)
--> 134             return wrapped(*args, **kwargs)
    135 

~\anaconda3\envs\ee\lib\site-packages\googleapiclient\http.py in execute(self, http, num_retries)
    914         if resp.status >= 300:
--> 915             raise HttpError(resp, content, uri=self.uri)
    916         return self.postproc(resp, content)

HttpError: <HttpError 400 when requesting https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/maps?fields=name&alt=json returned "Image.addBands, argument 'srcImg': Invalid type.
Expected type: Image<unknown bands>.
Actual type: ImageCollection.". Details: "Image.addBands, argument 'srcImg': Invalid type.
Expected type: Image<unknown bands>.
Actual type: ImageCollection.">

During handling of the above exception, another exception occurred:

EEException                               Traceback (most recent call last)
<ipython-input-48-2b5229b6e636> in <module>
      7 classified = image.select(parameter).classify(trained);
      8 class_vis={'min': 0, 'max': 4, 'palette': ['#d63000', '#4694d0','#ffc82d','#1e7c10','#dadada']}
----> 9 Map.addLayer(classified,class_vis,'classification');

~\anaconda3\envs\ee\lib\site-packages\geemap\geemap.py in add_ee_layer(self, ee_object, vis_params, name, shown, opacity)
   1288                 raise Exception(e)
   1289 
-> 1290         map_id_dict = ee.Image(image).getMapId(vis_params)
   1291         tile_layer = TileLayer(
   1292             url=map_id_dict["tile_fetcher"].url_format,

~\anaconda3\envs\ee\lib\site-packages\ee\image.py in getMapId(self, vis_params)
    129     vis_image, request = self._apply_visualization(vis_params)
    130     request['image'] = vis_image
--> 131     response = data.getMapId(request)
    132     response['image'] = self
    133     return response

~\anaconda3\envs\ee\lib\site-packages\ee\data.py in getMapId(params)
    573   # Make it return only the name field, as otherwise it echoes the entire
    574   # request, which might be large.
--> 575   result = _execute_cloud_call(
    576       _get_cloud_api_resource().projects().maps().create(
    577           parent=_get_projects_path(), fields='name', body=request))

~\anaconda3\envs\ee\lib\site-packages\ee\data.py in _execute_cloud_call(call, num_retries)
    334     return call.execute(num_retries=num_retries)
    335   except googleapiclient.errors.HttpError as e:
--> 336     raise _translate_cloud_exception(e)
    337 
    338 

EEException: Image.addBands, argument 'srcImg': Invalid type.
Expected type: Image<unknown bands>.
Actual type: ImageCollection.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
