### ISSUE TITLE
while exporting feature collection in csv format error is coming.

### ISSUE THREAD

**Issue by pawansingh1610** [google/earthengine-api#161]
Export.table.toDrive(**{
  'collection': feature_info,
  'fileFormat': 'CSV'
});  

error:<ipython-input-67-765623b8f37b> in <module>
----> 1 Export.table.toDrive(**{
      2   'collection': feature_info,
      3   'fileFormat': 'CSV'
      4 });  

NameError: name 'Export' is not defined

**Comment by tylere** [comment]
For information on getting help using Earth Engine, please visit: https://developers.google.com/earth-engine/help
