### ISSUE TITLE
Error get map with Angular.

### ISSUE THREAD

**Issue by PopescuGeorge94** [google/earthengine-api#165]
Hi, I tried to connect with Google Earth Engine from Angular 11 and I receive this error: Authentication error: TypeError: Cannot use 'in' operator to search for 'Object' in undefined.

if I remove min and max from getMap visParams object everything is ok.

Here is my code.
  public initializeGoogleEarthEngine(map: any) {

    var ee = require('@google/earthengine');
    // Load client library.

    // Initialize client library and run analysis.
    var initialize = () => {
      ee.initialize();
      console.log(ee);
      // Load EE image.
      const image = ee.Image('COPERNICUS/S2/20190813T094031_20190813T094222_T34TDR');
      console.log(image);
      image.getMap({min: 0, max: 1000}, (mapp): void => {
        console.log(map);
        var mapType = new ee.MapLayerOverlay(

          'https://earthengine.googleapis.com/map',
          mapp.mapid, mapp.token, {});
        // Add the EE layer to the map.
          
        map.overlayMapTypes.push(mapType);

      });
    };

    // Authenticate using an OAuth pop-up.
    ee.data.authenticateViaOauth('ID', initialize, function (e: any) {
      console.error('Authentication error: ' + e);
    }, null, function () {
      ee.data.authenticateViaPopup(initialize);
    });

  }

**Comment by donmccurdy** [comment]
With some build configurations (probably Webpack, in this case?) you may need to assign the `ee` object as a global. For example:

```js
var ee = window.ee = require('@google/earthengine');
```

Does that improve things? If not, can you share a more complete example or steps to reproduce the problem, including your project's build configuration?

**Comment by PopescuGeorge94** [comment]
Hi Don, thanks for your reply, I resolved the problem, I run script with
Node Js and everything is working fine.
