### ISSUE TITLE
NOTICE: Do not create new issues here.

### ISSUE THREAD

**Issue by NgoshaJr** [google/earthengine-api#166]
Hi guys
I got an error, plz someone to help me

AttributeError: module 'ee' has no attribute 'Reducer'

**Comment by fitoprincipe** [comment]
You don't have to create new issues here, but
1. I guess you are using the Python API
2. It seems like you did not initialize EE:
```
import ee
ee.Initialize()
reducer = ee.Reducer.mean()
```
should work

**Comment by bluesky314** [comment]
@fitoprincipe Why don't we have to create new issues here?

**Comment by intotecho** [comment]
Hi @NgoshaJr, 
For questions about using Earth Engine, you could try searching [gis.stackexchange.com] (https://gis.stackexchange.com/questions/tagged/google-earth-engine). If you can't find what you are looking for, then ask a question. It currently has 3,416 questions tagged google-earth-engine. Although there are 993 questions with no upvoted or accepted answers :( 

See also Earth Engine's [ask a question](https://developers.google.com/earth-engine/help#ask_a_question)

Only raise issues on this repo if you think there is a bug or want to suggest an enhancement to the earth engine api.

**Comment by 12rambau** [comment]
@fitoprincipe I think you should pin a fake issue mentioning your answer at the top of the issue panel.

**Comment by schwehr** [comment]
This is not the place to ask about how to use the clients. Closing.
