### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 

### ISSUE THREAD

**Issue by esyasi** [google/earthengine-api#168]
I am trying to connect to GEE Python API through Tethys platform. After following all the procedures like registering and whitelisting the service account, I get 404 error from Google Cloud. What could be possible reasons for the error? I have tried all the debugging that I can do, but getting the error time and again. Any comment would be helpful.

**Comment by tylere** [comment]
For information on getting help using Earth Engine, please visit: https://developers.google.com/earth-engine/help
