### ISSUE TITLE
Cannot install module via npm

### ISSUE THREAD

**Issue by plgagnon2** [google/earthengine-api#169]
https://runkit.com/embed/8kir4xyzsk74

**Comment by sufyanAbbasi** [comment]
Hello! Developer on the Earth Engine team here. Thank you very much for reporting this issue, we have found the source of the problem on our side and will release a new version with the fix soon and will update this thread when it's fixed.

**Comment by sufyanAbbasi** [comment]
Please sync to the latest version, [`v0.1.280`](https://www.npmjs.com/package/@google/earthengine); I have verified that the  issue is resolved in a local, fresh install.

I did rerun the above runkit test and found a different issue, however it's possible that there is an issue with the runtime environment causing the new problem:
https://runkit.com/embed/l3rog4s9ykda
