### ISSUE TITLE
problem installing earthengine-api

### ISSUE THREAD

**Issue by hrsuraj** [google/earthengine-api#17]
I followed the steps detailed in this site: https://developers.google.com/earth-engine/python_install

On step 4, I get the following error:
**Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-F7JE6P/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-iOQdC4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-F7JE6P/cryptography/**

After this, the command to set up authentication credentials throws the following error:
**Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named ee**

Please help.

**Comment by tylere** [comment]
The Python Installation steps have been updated since this issue was posted. Could you confirm whether or not you are still encountering an error while installing the Earth Engine API?

**Comment by brentonmallen1** [comment]
I've run into this issue after trying to execute the import in a notebook in the docker container listed in the `Python Installation` guide.  I did make a change to use docker-compose, however.
```
ImportError                               Traceback (most recent call last)
<ipython-input-7-05480dc2e261> in <module>()
----> 1 import ee

ImportError: No module named 'ee'```


My docker-compose file:
```
version: '3'
services:
  earth:
    image: gcr.io/earthengine-project/datalab-ee:latest
    env_file:
     - ./earth_engine.env
    ports:
      - 8081:8080
    volumes:
      - /path/to/datalab-ee:/content
```

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
