### ISSUE TITLE
How to crate Buffer collected Shapfile data and Raster

### ISSUE THREAD

**Issue by jaykeng** [google/earthengine-api#171]
I would like to generate the code in GEE to genarate the buffer that collected the point shapefile data and colected raster data at the same time then crate the graph to compare data fromShapfile and Raster file. I appriciate any recomend.

![image](https://user-images.githubusercontent.com/41981846/133118718-378abb4c-eea0-429b-9c7b-2cd743c132a3.png)
![image](https://user-images.githubusercontent.com/41981846/133119133-8a7b0e95-f52e-455b-af5f-7e15761b0ecc.png)

**Comment by tylere** [comment]
For information on getting help using Earth Engine, please visit: https://developers.google.com/earth-engine/help
