### ISSUE TITLE
reduceRegion not working on Sentinel5P

### ISSUE THREAD

**Issue by yreinhardt** [google/earthengine-api#174]
I am trying to get max value from every image in collection (Sentinel-5P) using reduceRegion. First there are multiple images for a single day... . Second if i add the max value i get None instead of an number. Thanks for help! 

import ee

ee.Initialize()
roi =  ee.Geometry.Polygon(
[[[-56.37397887990624, -12.737207954893526],
[-56.37397887990624, -13.300834158918619],
[-55.37113311574608, -13.300834158918619],
[-55.37113311574608, -12.737207954893526]]])

def max_red(img):
    max_dict = img.reduceRegion(
      reducer=ee.Reducer.max(),
      geometry= roi,
      scale=1200,
      maxPixels=1e13
    )
    return img.set({'max': max_dict})

band = 'SO2_column_number_density'
product ='COPERNICUS/S5P/OFFL/L3_SO2'
start = ee.Date('2019-01-01')
finish = ee.Date('2019-01-02')
collection = ee.ImageCollection(product).filterDate(start, finish).filterBounds(roi).select(band)

print("Collection size: ", collection.size().getInfo())

max_val_col = collection.map(max_red)
stats = max_val_col.aggregate_array('max').getInfo()

print("collection max value: ", stats)

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
