### ISSUE TITLE
Problem : Can't Parse the dataset

### ISSUE THREAD

**Issue by itsaliaze** [google/earthengine-api#177]
### **hello, i'm a python beginner... when i try to execute this part of the code :** 
`def parse_tfrecord(example_proto):
  """The parsing function.

  Read a serialized example into the structure defined by featuresDict.

  Args:
    example_proto: a serialized Example.

  Returns:
    A tuple of the predictors dictionary and the label, cast to an `int32`.
  """
  parsed_features = tf.io.parse_single_example(example_proto, features_dict)
  labels = parsed_features.pop(LABEL)
  return parsed_features, tf.cast(labels, tf.int32)

# Map the function over the dataset.
parsed_dataset = train_dataset.map(parse_tfrecord, num_parallel_calls=5)

# Print the first parsed record to check.
pprint(iter(parsed_dataset).next())`

### **i get this error :** 
InvalidArgumentError: Feature: Landcover (data type: float) is required but could not be found.
	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]] [Op:IteratorGetNext]

**### The training and testing data that i created is a simple table of landcover class (integer) starting from  1 to 3 ...**
CAN SOMEONE HELP ME PLEASE !!

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
