### ISSUE TITLE
key_data argument ignored by ServiceAccountCredentials function

### ISSUE THREAD

**Issue by azvoleff** [google/earthengine-api#18]
The `ServiceAccountCredentials` function docstring claims to support supplying the `key_data` argument instead of `key_file` to directly supply a PEM key to this function. However, as coded, this option does not work, as a TypeError is raised if key_file is not supplied.

See: https://github.com/google/earthengine-api/blob/1231f1c9b905a07bbd63cbd2ed6263b430e51460/python/ee/_helpers.py#L45

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
