### ISSUE TITLE
ee.Initialize() raises `AttributeError: module 'collections' has no attribute 'Callable'` on Python 3.10

### ISSUE THREAD

**Issue by arkanoid87** [google/earthengine-api#181]
get or use python 3.10, I use pyenv

`pyenv local 3.10.2`

Init venv, install package, authenticate and Initialize
```
python -m venv venv
source venv/bin/activate
pip install earthengine-api
python3 -c "import ee; ee.Authenticate(); ee.Initialize()"
```
output:
`AttributeError: module 'collections' has no attribute 'Callable'`

pip freeze:
```
cachetools==5.0.0
certifi==2021.10.8
charset-normalizer==2.0.12
earthengine-api==0.1.304
future==0.18.2
google-api-core==2.7.1
google-api-python-client==1.12.11
google-auth==2.6.2
google-auth-httplib2==0.1.0
google-cloud-core==2.2.3
google-cloud-storage==2.2.1
google-crc32c==1.3.0
google-resumable-media==2.3.2
googleapis-common-protos==1.56.0
httplib2==0.20.4
httplib2shim==0.0.3
idna==3.3
protobuf==3.20.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.7
requests==2.27.1
rsa==4.8
six==1.16.0
uritemplate==3.0.1
urllib3==1.26.9
```

dirty workaround:
```
import collections
collections.Callable = collections.abc.Callable
```

**Comment by Skrapnell7** [comment]
I encountered the same issue "AttributeError: module 'collections' has no attribute 'Callable'" error when I ran " ee.Initialize() " (after successfully authenticating ee) from my  Jupyter Lab (notebook), within a Virtual Environment, using Python=3.10. 
The only way I could work around this error was to use an older version of Python=3.7.8 in my Virtual Environment.

**Comment by jessjaco** [comment]
Apparently solved https://issuetracker.google.com/issues/222122916

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
