### ISSUE TITLE
How to Normalize Sentinel data for ML downstream

### ISSUE THREAD

**Issue by skr3178** [google/earthengine-api#183]
I am working on a sentinel 2 dataset in the application to use the images for classification.

The dataset I have is in numpy array (13,40,40) containing information on the 12 bands (B1-B12) as described [here](https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2#bands).

Some of the bands are in RGB (B2, B3, B4) which can be normalized by the typically used 255.0 (uint8). My question is how to select the value for normalizing the other bands (!B2, B3, B4) in the given list of B1-B12.

Thanks so much for helping me.

**Comment by simonff** [comment]
This question is better suited for the developers forum or Stack Exchange - [please see this](https://developers.google.com/earth-engine/help#ask_a_question).
