### ISSUE TITLE
http 403 error

### ISSUE THREAD

**Issue by skr3178** [google/earthengine-api#184]
hi, 
When I run this code i get an error. I have already created a new account for google earth engine
https://github.com/google/earthengine-api/blob/6445cae4c371a8244f70ae08c01a6da05dbc4c7d/python/examples/ipynb/Earth_Engine_TensorFlow_logistic_regression.ipynb

i get error 
![image](https://user-images.githubusercontent.com/79299617/167267668-3b039c14-05a3-46c0-9d3f-79bed3c40f10.png)

which when expanded
![image](https://user-images.githubusercontent.com/79299617/167267694-9133234a-6a00-4f50-bad0-510164144cdd.png)
![image](https://user-images.githubusercontent.com/79299617/167267699-3b0795d7-bfd4-4730-a8c6-3311a7cd7b02.png)
![image](https://user-images.githubusercontent.com/79299617/167267707-7c5ebbb2-a202-4413-acf3-f99d4b21614b.png)

**Comment by simonff** [comment]
This question is better suited for the developers forum or Stack Exchange - [please see this](https://developers.google.com/earth-engine/help#ask_a_question).
