### ISSUE TITLE
exporting data using service account

### ISSUE THREAD

**Issue by oyogo** [google/earthengine-api#188]
Hi,
I am running a python script authenticated by a service account I created using my email. The problem I am having is I am using ee.batch.Export.image.toDrive function but I don't know where the data is sent to though the script is running successfully. I was hoping to see it in my emails' google drive but it's not there. Where is the data exported to?

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
