### ISSUE TITLE
earthengine-api/demos/forest/scripts/README.md

### ISSUE THREAD

**Issue by sabrinaszeto** [google/earthengine-api#19]
I was following the instructions in earthengine-api/demos/forest/scripts/README.md and when I tried to serve using Polymer the following error message appeared, "Polymer CLI requires at least Node v6. You have v4.8.3." 

Thus, I suggest changing the instructions from "$ nvm install 4" to "$ nvm install 6".

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
