### ISSUE TITLE
This sentence [raise from] is making trouble in python27, hope you can use it in a different way or include the use of future in order not to get error when trying to import the api from python27

### ISSUE THREAD

**Issue by jorgeluisyh** [google/earthengine-api#192]
https://github.com/google/earthengine-api/blob/2d0f9c495da336d1209f57c1b2d5f9fc978c94cb/python/ee/_cloud_api_utils.py#L365

**Comment by schwehr** [comment]
This package now only supports python >= 3.7. Python 2.7 is specifically not supported. Closing.
