### ISSUE TITLE
Sign In Using Gcloud without having access to a computer with browser.

### ISSUE THREAD

**Issue by JuanDiaz12000** [google/earthengine-api#195]
Hello. I'm helping in the development of a docker flask app that uses the google earth engine api. Although we know a ee.authenticate alternative would be using service account credentials, we would like the users to use their personal account. However, as we don't want the user to install themselves using gcloud on their personal machines, we receive a 403 error from ee qs that sign in method is not allowed. Is there anyway to sign in without having access to a web browser that does not need the use of service accounts?

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
