### ISSUE TITLE
Does MultiPolygon support Altitude?

### ISSUE THREAD

**Issue by hanshupe** [google/earthengine-api#197]
I have a GeoJSON of type MultiPolygon that includes altitudes. When loading it with earth engine (ee.FeatureCollection), I receive an error, that the Geometry is invalid. The underlying code suggests that the MultiPolygon must only have arrays of 2 elements.

This is an example MultiPolygon I am using:` [[[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]]]
`
Does MultiPloygon only supports 2D coordinates?

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
