### ISSUE TITLE
Upgrade setup.py to pyproject.toml

### ISSUE THREAD

**Issue by davidcavazos** [google/earthengine-api#202]
Installing `earthengine-api` gives a deprecation warning because Earth Engine uses a `setup.py` file to configure the installation, which will be deprecated in `pip` 23.1 in favor of a `pyproject.toml` file.

How to reproduce:

```sh
python -m venv env
source env/bin/activate

pip install earthengine-api
```

Shows the following warning:

`DEPRECATION: earthengine-api is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559`

`pip` version [23.1 is targeted to release by April 30](https://github.com/pypa/pip/milestone/68), by then the `setup.py` file will be deprecated.

[PEP-621](https://peps.python.org/pep-0621) describes more context on why this change and how to upgrade. The good news is that the `pyproject.toml` file is declarative instead of containing arbitrary code, which makes writing it and maintaining it much simpler than the `setup.py` file.

**Comment by schwehr** [comment]
Thanks for the issue report. We are closing the issue here, but have it tracked internally.
