### ISSUE TITLE
Connection pool is full, discarding connection: earthengine.googleapis.com. Connection pool size: 1

### ISSUE THREAD

**Issue by mebibou** [google/earthengine-api#203]
I run queries to Earth Engine in parallel using multi-threading:

```python
ee.Initialize(ee.ServiceAccountCredentials(EE_ACCOUNT_ID, EE_KEY_FILE))

with ThreadPoolExecutor() as executor:
    run_query()
```

Very often, I see this warning:
```
Connection pool is full, discarding connection: earthengine.googleapis.com. Connection pool size: 1
```

Is there a way to change the pool size? or any other way to handle multi threading requests?

**Comment by mebibou** [comment]
You mean limit it to the pool size which seems to be `1`? kinda defeats the whole point of multi-threading

**Comment by alhridoy** [comment]
Yes! i belive that Earth Engine kept the pool size to be 1.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
