### ISSUE TITLE
earthengine-api 0.1.365 not working with Python 3.8

### ISSUE THREAD

**Issue by giswqs** [google/earthengine-api#212]
earthengine-api v0.1.365 released today breaks Python 3.8.   @naschmitz 

https://pypi.org/project/earthengine-api/0.1.365/

```bash
conda create -n py38 python=3.8
conda activate py38
pip install -U earthengine-api
python
import ee
```

![image](https://github.com/google/earthengine-api/assets/5016453/1fc521c2-9379-4196-9f43-75eae21c0c7d)

https://github.com/gee-community/geemap/pull/1674

**Comment by bengalin** [comment]
See also PR #211 . We will fix internally and push a new version to here, PyPI, and conda-forge.  Expect to have this done by tomorrow.  Sorry for the disruption.  Please use `v0.1.364` meanwhile.

**Comment by giswqs** [comment]
Great to hear that the fix is already implemented. Thank you.

**Comment by schwehr** [comment]
We missed one thing with the prior release. The [release from this afternoon (0.1.367)](https://github.com/google/earthengine-api/commit/7aa25b20403d6951588f985de24363f657e780c2) passes the geemap tests (except docs) in my fork.
