### ISSUE TITLE
EEException: Cannot get size for asset type "Table"

### ISSUE THREAD

**Issue by tracek** [google/earthengine-api#24]
Execution of `earthengine du` produces: 

> EEException: Cannot get size for asset type "Table"

https://github.com/google/earthengine-api/blob/dad6f93cdc665a04fbbb454370a543873d9a5e5e/python/ee/cli/commands.py#L704

The fix seems to be very easy: extend `size_parsers` to handle Tables. Since the function to handle it would be exactly the same as for `_get_size_image` (or at least that's my impression), I would propose to rename the function to `_get_size_asset` and add Table to parsers, e.g.:

```
size_parsers = {
    'Image': _get_size_asset,
    'Folder': _get_size_folder,
    'ImageCollection': _get_size_image_collection,
    'Table': _get_size_asset
}

def _get_size_asset(asset):
    info = ee.data.getInfo(asset['id'])
    return info['properties']['system:asset_size']
```

**Comment by gena** [comment]
There is actually a pull request for this: #23, someone with the access just needs to merge it.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
