### ISSUE TITLE
importing EE javascript api into another javascript script--and not through html

### ISSUE THREAD

**Issue by 00krishna** [google/earthengine-api#26]
Hey Folks. 
This is really more a question than an issue, but I though others might benefit. The javascript demos posted all have the js "application" accessing/importing the EE javascript api through the script tag
`<script src="/static/ee_api_js.js"></script>`. I was wondering how to import this `ee_api_js.js` file directly into a javascript script--and avoiding the html? I did not see any demos that did that. 

So say I want to execute the code below to download a url without going through html.
```
var mymod = require('/../javascript/ee_api_js');

var image = mymod.Image('srtm90_v4');
var path = image.getDownloadURL({
    'scale': 30,
    'crs': 'EPSG:4326',
    'region': '[[-120, 35], [-119, 35], [-119, 34], [-120, 34]]'
});
print(path);
```
But I get an error:

```
var image = mymod.Image('srtm90_v4');
                  ^
TypeError: mymod.Image is not a function
```

**Comment by gena** [comment]
For Node.js applications, you can try [ee-runner](https://github.com/gena/ee-runner). However, it mainly targets server-side and command-line apps and not web apps. For web apps, require() is still a [relatively new](https://medium.com/dev-channel/es6-modules-in-chrome-canary-m60-ba588dfb8ab7) feature, it may be better to still merge everything using something like Rollup or Webpack, to make sure it works with legacy browsers.

**Comment by 00krishna** [comment]
@gena thanks for the tip about ee-runner. I had not seen that. Yeah, I want to avoid using a browser, so need to be able to run this code through pure node or something. With ee-runner, how do I pass the authentication info? I figure I would need to pass that before rest of the code above would work.

**Comment by gena** [comment]
When you start it for the first time - it will print instruction required for authentication, if necessary.

**Comment by tylere** [comment]
@00krishna did @gena 's answer resolve your issue?

**Comment by donmccurdy** [comment]
The Earth Engine JS library is now available on NPM. See: 

- https://developers.google.com/earth-engine/npm_install
- https://www.npmjs.com/package/@google/earthengine

```js
var ee = require('@google/earthengine');
```
