### ISSUE TITLE
Unable to initialize the GEE python client while processing "ee.Initialize()"

### ISSUE THREAD

**Issue by YinuoJin** [google/earthengine-api#27]
I installed the Google Earthengine python client and attempted to use the API, but I met some problems when I tried to initialize the client library by typing **"ee.Initialize()"** in python. Here is the detail of the error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/ee/__init__.py", line 93, in Initialize
    ApiFunction.initialize()
  File "/anaconda3/lib/python3.6/site-packages/ee/apifunction.py", line 151, in initialize
    signatures = data.getAlgorithms()
  File "/anaconda3/lib/python3.6/site-packages/ee/data.py", line 420, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "/anaconda3/lib/python3.6/site-packages/ee/data.py", line 819, in send_
    response.status)
ee.ee_exception.EEException: Server returned HTTP code: 404`

The following is the specific procedure of my installation:
## (1) check the current python version:
`python --version`
`Python 3.6.2 :: Anaconda custom (64-bit)`

## (2) install the google api python client library by pip:
<details>
<summary>sudo pip install google-api-python-client</summary>

    The directory '/Users/yinuo/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/Users/yinuo/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Collecting google-api-python-client
      Downloading google_api_python_client-1.6.4-py2.py3-none-any.whl (53kB)
        100% |████████████████████████████████| 61kB 577kB/s 
    Requirement already satisfied: six<2dev,>=1.6.1 in /anaconda3/lib/python3.6/site-packages (from google-api-python-client)
    Collecting oauth2client<5.0.0dev,>=1.5.0 (from google-api-python-client)
      Downloading oauth2client-4.1.2-py2.py3-none-any.whl (99kB)
        100% |████████████████████████████████| 102kB 615kB/s 
    Collecting httplib2<1dev,>=0.9.2 (from google-api-python-client)
    Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /anaconda3/lib/python3.6/site-packages (from google-api-python-client)
    Collecting rsa>=3.1.4 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client)
      Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
        100% |████████████████████████████████| 51kB 612kB/s 
    Collecting pyasn1-modules>=0.0.5 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client)
      Downloading pyasn1_modules-0.1.5-py2.py3-none-any.whl (60kB)
        100% |████████████████████████████████| 61kB 611kB/s 
    Collecting pyasn1>=0.1.7 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client)
      Downloading pyasn1-0.3.7-py2.py3-none-any.whl (63kB)
        100% |████████████████████████████████| 71kB 695kB/s 
    Installing collected packages: pyasn1, rsa, httplib2, pyasn1-modules, oauth2client, google-api-python-client
    Successfully installed google-api-python-client-1.6.4 httplib2-0.10.3 oauth2client-4.1.2 pyasn1-0.3.7 pyasn1-modules-0.1.5 rsa-3.4.2
</details>

## (3) check the availability of crypto and install pyCrypto:
`python -c "from oauth2client import crypt"`

<details>
<summary>sudo pip install pyCrypto</summary>

    The directory '/Users/yinuo/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/Users/yinuo/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Collecting pyCrypto
      Downloading pycrypto-2.6.1.tar.gz (446kB)
        100% |████████████████████████████████| 450kB 464kB/s 
    Installing collected packages: pyCrypto
      Running setup.py install for pyCrypto ... done
    Successfully installed pyCrypto-2.6.1
</details>

## (4) install the earthengine python api:

<details>
<summary>sudo pip install earthengine-api</summary>

    The directory '/Users/yinuo/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/Users/yinuo/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Collecting earthengine-api
      Downloading earthengine-api-0.1.127.tar.gz (90kB)
        100% |████████████████████████████████| 92kB 550kB/s 
    Requirement already satisfied: google-api-python-client in /anaconda3/lib/python3.6/site-packages (from earthengine-api)
    Collecting pyOpenSSL>=0.11 (from earthengine-api)
      Downloading pyOpenSSL-17.3.0-py2.py3-none-any.whl (51kB)
        100% |████████████████████████████████| 51kB 307kB/s 
    Requirement already satisfied: oauth2client<5.0.0dev,>=1.5.0 in /anaconda3/lib/python3.6/site-packages (from google-api-python-client->earthengine-api)
    Requirement already satisfied: six<2dev,>=1.6.1 in /anaconda3/lib/python3.6/site-packages (from google-api-python-client->earthengine-api)
    Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /anaconda3/lib/python3.6/site-packages (from google-api-python-client->earthengine-api)
    Requirement already satisfied: httplib2<1dev,>=0.9.2 in /anaconda3/lib/python3.6/site-packages (from google-api-python-client->earthengine-api)
    Collecting cryptography>=1.9 (from pyOpenSSL>=0.11->earthengine-api)
      Downloading cryptography-2.1.2-cp36-cp36m-macosx_10_6_intel.whl (1.5MB)
        100% |████████████████████████████████| 1.5MB 325kB/s 
    Requirement already satisfied: rsa>=3.1.4 in /anaconda3/lib/python3.6/site-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client->earthengine-api)
    Requirement already satisfied: pyasn1>=0.1.7 in /anaconda3/lib/python3.6/site-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client->earthengine-api)
    Requirement already satisfied: pyasn1-modules>=0.0.5 in /anaconda3/lib/python3.6/site-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client->earthengine-api)
    Collecting idna>=2.1 (from cryptography>=1.9->pyOpenSSL>=0.11->earthengine-api)
      Downloading idna-2.6-py2.py3-none-any.whl (56kB)
        100% |████████████████████████████████| 61kB 634kB/s 
    Collecting asn1crypto>=0.21.0 (from cryptography>=1.9->pyOpenSSL>=0.11->earthengine-api)
      Downloading asn1crypto-0.23.0-py2.py3-none-any.whl (99kB)
        100% |████████████████████████████████| 102kB 529kB/s 
    Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.9->pyOpenSSL>=0.11->earthengine-api)
      Downloading cffi-1.11.2-cp36-cp36m-macosx_10_6_intel.whl (240kB)
        100% |████████████████████████████████| 245kB 493kB/s 
    Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.9->pyOpenSSL>=0.11->earthengine-api)
      Downloading pycparser-2.18.tar.gz (245kB)
        100% |████████████████████████████████| 256kB 519kB/s 
    Installing collected packages: idna, asn1crypto, pycparser, cffi, cryptography, pyOpenSSL, earthengine-api
      Running setup.py install for pycparser ... done
      Running setup.py install for earthengine-api ... done
    Successfully installed asn1crypto-0.23.0 cffi-1.11.2 cryptography-2.1.2 earthengine-api-0.1.127 idna-2.6 pyOpenSSL-17.3.0 pycparser-2.18
</details>

## (5) setting up authentication credentials:

<details>
<summary>python -c "import ee; ee.Initialize()"</summary>

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/anaconda3/lib/python3.6/site-packages/ee/__init__.py", line 93, in Initialize
        ApiFunction.initialize()
      File "/anaconda3/lib/python3.6/site-packages/ee/apifunction.py", line 151, in initialize
        signatures = data.getAlgorithms()
      File "/anaconda3/lib/python3.6/site-packages/ee/data.py", line 420, in getAlgorithms
        return send_('/algorithms', {}, 'GET')
      File "/anaconda3/lib/python3.6/site-packages/ee/data.py", line 819, in send_
        response.status) 
    ee.ee_exception.EEException: Server returned HTTP code: 404
</details>

<details>
<summary>earthengine authenticate</summary>

    Opening the following address in a web browser:
        https://accounts.google.com/o/oauth2/auth?client_id=517222506229-vsmmajv00ul0bs7p89v5m89qs8eb9359.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fearthengine+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code
    Please authorize access to your Earth Engine account, and paste the generated code below. If the web browser does not start, please manually browse the URL above.
    Please enter authorization code: 4/UUOevaSPstLHwa4tsK9gDDIkD0eJu8nPYrtSh9whWJ8
    Successfully saved authorization token.
</details>

## (6) open the command-line version of python & check whether the GEE api is successfully installed:

<details>
<summary>Command-line test details</summary>

    python
    Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 21 2017, 18:29:43) 
    [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ee
    >>> ee.Initialize()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/anaconda3/lib/python3.6/site-packages/ee/__init__.py", line 93, in Initialize
        ApiFunction.initialize()
      File "/anaconda3/lib/python3.6/site-packages/ee/apifunction.py", line 151, in initialize
        signatures = data.getAlgorithms()
      File "/anaconda3/lib/python3.6/site-packages/ee/data.py", line 420, in getAlgorithms
        return send_('/algorithms', {}, 'GET')
      File "/anaconda3/lib/python3.6/site-packages/ee/data.py", line 819, in send_
        response.status)
    ee.ee_exception.EEException: Server returned HTTP code: 404
</details>

As it shows, the problem still exists even after I processed the credentials authentication. One potential problem might be that I installed python via anaconda, so there might be two different python paths (one system python, and another python under the anaconda directory). I'm not sure what the actually problem is and thanks a lot for your help!

**Comment by tylere** [comment]
I was unable to replicate the issue using Anaconda3-5.0.1 on an OSX machine. Note that I did not need to use 'sudo' when using pip to install the Python packages.

During the `earthengine authenticate` step, did you use a Google account that is whitelisted to use Earth Engine? I.e. can you access [code.earthengine.google.com](code.earthengine.google.com) with that account?

**Comment by YinuoJin** [comment]
Hi Tyler, I tried to access the link you posted, but unfortunately it still shows that my account doesn't  appear to be registered for Earth Engine access. Nick emailed me earlier this week that my account had been added to use GEE, so is it possible for you to check that whether I'm on the whitelist or not? Thanks a lot for your help!

**Comment by VickyVanthof** [comment]
I am having the same issue as above except my account if accessible by code.earthengine.google.com . Any solutions to me problem?

**Comment by tylere** [comment]
@YinuoJin @VickyVanthof are you still experiencing this issue?

**Comment by langwh** [comment]
I am having the same issue as above

**Comment by GuohuaHu** [comment]
I am having the same issue as above

**Comment by tylere** [comment]
To test whether or not your Google account is correctly whitelisted to access Earth Engine, please open up a new browser window (such as an incognito window in the Chrome browser) try to log into the Earth Engine Code Editor: https://code.earthengine.google.com/

Are you able to successfully log into the Code Editor?

**Comment by YinuoJin** [comment]
Yes, I can log into the editor successfully!

**Comment by Zundrits** [comment]
I am having the same issue as above for initializing a service_account ee. EE with user account did not throw this issue.

**Comment by vool** [comment]
Same issue here

**Comment by Kathiya** [comment]
i also have same issue but i am using python 3.7.2

**Comment by brentonmallen1** [comment]
I'm seeing the same issue.  I've gone through the steps listed [here](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#creatinganaccount)

I'm not sure if the registration takes some time, but I am able to access the code editor from the account.

Environment:
```
absl-py==0.7.0
affine==2.2.2
alabaster==0.7.12
altair==2.4.1
aniso8601==4.1.0
appnope==0.1.0
asn1crypto==0.24.0
astor==0.7.1
asyncssh==1.16.1
atomicwrites==1.3.0
attrs==18.2.0
Babel==2.6.0
backcall==0.1.0
bleach==3.1.0
boto3==1.9.101
botocore==1.12.101
branca==0.3.1
cachetools==2.1.0
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
Click==7.0
click-plugins==1.0.4
cligj==0.5.0
cloudpickle==0.8.0
commonmark==0.8.1
cryptography==2.6.1
cycler==0.10.0
cytoolz==0.9.0.1
daiquiri==1.5.0
dask==1.1.2
decorator==4.3.2
descartes==1.1.0
docutils==0.14
earthengine-api==0.1.173
entrypoints==0.3
Fiona==1.8.6
Flask==1.0.2
Flask-Cors==3.0.7
Flask-JWT==0.3.2
Flask-RESTful==0.3.7
folium==0.8.3
fpdf==1.7.2
future==0.17.1
gast==0.2.2
GDAL==2.4.1
geopandas==0.5.0
google-api-python-client==1.7.8
google-auth==1.6.3
google-auth-httplib2==0.0.3
grpcio==1.16.1
h5py==2.9.0
httplib2==0.12.3
idna==2.8
imageio==2.5.0
imagesize==1.1.0
ipykernel==5.1.0
ipython==7.3.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
jedi==0.13.3
Jinja2==2.10
jmespath==0.9.3
joblib==0.13.2
jsonschema==3.0.1
jupyter-client==5.2.4
jupyter-core==4.4.0
jupyterlab==0.35.6
jupyterlab-server==0.2.0
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
Mako==1.0.7
mapclassify==2.0.1
Markdown==2.4.1
MarkupSafe==1.1.1
matplotlib==3.0.3
mistune==0.8.4
mock==3.0.4
more-itertools==4.3.0
munch==2.3.2
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.2
notebook==5.7.4
numpy==1.16.3
oauth2client==4.1.3
olefile==0.46
packaging==19.0
palettable==3.1.1
pandas==0.24.2
pandocfilters==1.4.2
parso==0.3.4
patsy==0.5.1
pbr==5.1.3
pdoc==0.3.2
pexpect==4.6.0
pickleshare==0.7.5
Pillow==6.0.0
pluggy==0.9.0
prometheus-client==0.6.0
prompt-toolkit==2.0.9
protobuf==3.6.1
psycopg2==2.7.7
psycopg2-binary==2.7.7
ptyprocess==0.6.0
py==1.8.0
pyasn1==0.4.4
pyasn1-modules==0.2.4
pycparser==2.19
Pygments==2.3.1
pygpu==0.7.6
PyJWT==1.7.1
pyOpenSSL==19.0.0
pyparsing==2.3.1
pyproj==2.1.3
pyrsistent==0.14.11
pysal==2.0.0
PySocks==1.6.8
pytest==4.4.1
python-dateutil==2.8.0
python-gnupg==0.4.4
python-http-client==3.1.0
pytz==2018.9
PyWavelets==1.0.3
PyYAML==3.13
pyzmq==18.0.0
rasterio==1.0.22
rasterstats==0.13.1
recommonmark==0.5.0
requests==2.21.0
rsa==3.4.2
Rtree==0.8.3
s3transfer==0.2.0
scikit-image==0.15.0
scikit-learn==0.20.3
scipy==1.2.1
seaborn==0.9.0
Send2Trash==1.5.0
sendgrid==5.6.0
Shapely==1.6.4.post2
simplejson==3.16.1
simplekml==1.3.1
six==1.12.0
snowballstemmer==1.2.1
snuggs==1.4.3
Sphinx==2.0.1
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.1
SQLAlchemy==1.2.18
statsmodels==0.9.0
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.4.2
Theano==1.0.3
toolz==0.9.0
tornado==5.1.1
tqdm==4.31.1
traitlets==4.3.2
uritemplate==3.0.0
urllib3==1.24.1
uWSGI==2.0.18
vincent==0.4.4
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
wget==3.2
xarray==0.12.1
```

**Comment by noeliaoses** [comment]
I am having a very similar issue:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/noses/miniconda3/envs/eeconda/lib/python3.7/site-packages/ee/__init__.py", line 123, in Initialize
    ApiFunction.initialize()
  File "/home/noses/miniconda3/envs/eeconda/lib/python3.7/site-packages/ee/apifunction.py", line 154, in initialize
    signatures = data.getAlgorithms()
  File "/home/noses/miniconda3/envs/eeconda/lib/python3.7/site-packages/ee/data.py", line 951, in getAlgorithms
    return _cloud_api_utils.convert_algorithms(_execute_cloud_call(call))
  File "/home/noses/miniconda3/envs/eeconda/lib/python3.7/site-packages/ee/data.py", line 326, in _execute_cloud_call
    raise _translate_cloud_exception(e)
ee.ee_exception.EEException: Permission denied.

In my google account permissions both Earth Engine Code Editor and Google Earth Engine Python Authenticator appear in my trusted installed google apps. However, I can't access neither  https://code.earthengine.google.com/ nor the python API.

I am using python 3.7.3 and I installed the ee package with miniconda following the instructions in https://developers.google.com/earth-engine/python_install-conda.html

**Comment by tylere** [comment]
Hi @noeliaoses,

Because you also cannot access the Earth Engine Code Editor, It is unlikely this is related to using the Python API.  Please send the account name to earthengine@google.com, and we can help you debug your login issue.

Cheers,
Tyler

**Comment by noeliaoses** [comment]
Dear Tyler,

Thank you for the reply. The account in question is noses@vicomtech.org. I
have sent it to earthengine@google.com a couple of times but to no avail. I
have not received any replies.

Best regards,
Noelia

**Comment by viswanathanc** [comment]
I got the same error. It was resolved when i signed up for Google Earth Engine.

**Comment by erfan-1995** [comment]
I get the same error when executing "ee.Initialize()" :
HttpError: <HttpError 403 when requesting https://earthengine.googleapis.com/$discovery/rest?version=v1alpha&prettyPrint=false returned "Forbidden">
Does anyone know the cause of this error and how to fix it?

**Comment by tylere** [comment]
@erfan-1995 we have been transitioning away from using GitHub issues for assisting with error message. Please see the following for resources:
https://developers.google.com/earth-engine/help#error_messages

**Comment by marcus3344** [comment]
@erfan-1995 l have the same Issue, also when I open this link in a new tab, this folliwing text is shown

{
  "error": {
    "code": 403,
    "message": "The request is missing a valid API key.",
    "status": "PERMISSION_DENIED"
  }
}

How can I fix it?

**Comment by alirezaghader** [comment]
@erfan-1995  Did u solve the issue? I experienced the exact same error.

googleapiclient.errors.HttpError: <HttpError 403 when requesting https://earthengine.googleapis.com/$discovery/rest?version=v1alpha&prettyPrint=false returned "Forbidden">

**Comment by erfan-1995** [comment]
hey there,
yes I did, it turns out I needed my VPN to be connected !

**Comment by marcus3344** [comment]
No, unfortunately I can't

**Comment by MahyaSad** [comment]
@erfan-1995 would you let me know which VPN you used for solving the problem? I have used different type of VPN but I still have this problem.

**Comment by mhoney97** [comment]
I am experiencing the same error, the Google Earth Engine library successfully authenticates in Python (I am running version 3.10), however the command 'ee.Initialize' returns the following error: 
File "C:\Users\redacted\AppData\Local\Programs\Python\Python310\lib\site-packages\ee\__init__.py", line 116, in Initialize
    data.initialize(
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python310\lib\site-packages\ee\data.py", line 199, in initialize
    _install_cloud_api_resource()
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python310\lib\site-packages\ee\data.py", line 266, in _install_cloud_api_resource
    _cloud_api_resource = _cloud_api_utils.build_cloud_resource(
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python310\lib\site-packages\ee\_cloud_api_utils.py", line 134, in build_cloud_resource
    http_transport = httplib2.Http(timeout=timeout)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python310\lib\site-packages\httplib2shim\__init__.py", line 117, in __init__
    pool = self._make_pool(proxy_info=proxy_info)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python310\lib\site-packages\httplib2shim\__init__.py", line 45, in _default_make_pool
    if isinstance(proxy_info, collections.Callable):
AttributeError: module 'collections' has no attribute 'Callable'

**Comment by mhoney97** [comment]
Update: I was able to resolve the error by uninstalling Python and reinstalling with Anaconda. Then, I installed earthengine-api in the Anaconda Prompt (pip install earthengine-api). Resetting everything took awhile, but it was definitely worth it!

**Comment by wzh1895** [comment]
It seems to have to do with the removal of some features in Python 3.10. A solution found at https://stackoverflow.com/questions/69515086/beautifulsoup-attributeerror-collections-has-no-attribute-callable solved my problem.

**Comment by Pietrahan** [comment]
Hi everyone, I have errors when I start ee.Initialize() 
this error :
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\anaconda3\lib\site-packages\ee\_cloud_api_utils.py in build_cloud_resource(api_base_url, api_key, credentials, timeout, headers_supplier, response_inspector, http_transport, raw)
    159     # package version, either.
--> 160     resource = build(static_discovery=False)
    161   except TypeError:

~\anaconda3\lib\site-packages\ee\_cloud_api_utils.py in build(**kwargs)
    153         cache_discovery=False,
--> 154         **kwargs)  # pytype: disable=wrong-keyword-args
    155 

~\anaconda3\lib\site-packages\googleapiclient\_helpers.py in positional_wrapper(*args, **kwargs)
    133                     logger.warning(message)
--> 134             return wrapped(*args, **kwargs)
    135 

TypeError: build() got an unexpected keyword argument 'static_discovery'

During handling of the above exception, another exception occurred:

RefreshError                              Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_9988\1766757204.py in <module>
----> 1 ee.Initialize()

~\anaconda3\lib\site-packages\ee\__init__.py in Initialize(credentials, opt_url, cloud_api_key, http_transport, project)
    128       cloud_api_key=cloud_api_key,
    129       project=project,
--> 130       http_transport=http_transport)
    131   # Initialize the dynamically loaded functions on the objects that want them.
    132   ApiFunction.initialize()

~\anaconda3\lib\site-packages\ee\data.py in initialize(credentials, api_base_url, tile_base_url, cloud_api_base_url, cloud_api_key, project, http_transport)
    201   _http_transport = http_transport
    202 
--> 203   _install_cloud_api_resource()
    204 
    205   if project is not None:

~\anaconda3\lib\site-packages\ee\data.py in _install_cloud_api_resource()
    267       headers_supplier=_make_request_headers,
    268       response_inspector=_handle_profiling_response,
--> 269       http_transport=_http_transport)
    270 
    271   _cloud_api_resource_raw = _cloud_api_utils.build_cloud_resource(

~\anaconda3\lib\site-packages\ee\_cloud_api_utils.py in build_cloud_resource(api_base_url, api_key, credentials, timeout, headers_supplier, response_inspector, http_transport, raw)
    160     resource = build(static_discovery=False)
    161   except TypeError:
--> 162     resource = build()
    163   resource._baseUrl = api_base_url
    164   return resource

~\anaconda3\lib\site-packages\ee\_cloud_api_utils.py in build(**kwargs)
    152         model=alt_model,
    153         cache_discovery=False,
--> 154         **kwargs)  # pytype: disable=wrong-keyword-args
    155 
    156   try:

~\anaconda3\lib\site-packages\googleapiclient\_helpers.py in positional_wrapper(*args, **kwargs)
    132                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    133                     logger.warning(message)
--> 134             return wrapped(*args, **kwargs)
    135 
    136         return positional_wrapper

~\anaconda3\lib\site-packages\googleapiclient\discovery.py in build(serviceName, version, http, discoveryServiceUrl, developerKey, model, requestBuilder, credentials, cache_discovery, cache, client_options, adc_cert_path, adc_key_path, num_retries)
    274                 cache,
    275                 developerKey,
--> 276                 num_retries=num_retries,
    277             )
    278             service = build_from_document(

~\anaconda3\lib\site-packages\googleapiclient\discovery.py in _retrieve_discovery_doc(url, http, cache_discovery, cache, developerKey, num_retries)
    374     # Note that it will already raise an error if we don't get a 2xx response
    375     req = HttpRequest(http, HttpRequest.null_postproc, actual_url)
--> 376     resp, content = req.execute(num_retries=num_retries)
    377 
    378     try:

~\anaconda3\lib\site-packages\googleapiclient\_helpers.py in positional_wrapper(*args, **kwargs)
    132                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    133                     logger.warning(message)
--> 134             return wrapped(*args, **kwargs)
    135 
    136         return positional_wrapper

~\anaconda3\lib\site-packages\googleapiclient\http.py in execute(self, http, num_retries)
    907             method=str(self.method),
    908             body=self.body,
--> 909             headers=self.headers,
    910         )
    911 

~\anaconda3\lib\site-packages\googleapiclient\http.py in _retry_request(http, num_retries, req_type, sleep, rand, uri, method, *args, **kwargs)
    175         try:
    176             exception = None
--> 177             resp, content = http.request(uri, method, *args, **kwargs)
    178         # Retry on SSL errors and socket timeout errors.
    179         except _ssl_SSLError as ssl_error:

~\anaconda3\lib\site-packages\google_auth_httplib2.py in request(self, uri, method, body, headers, redirections, connection_type, **kwargs)
    207         request_headers = headers.copy() if headers is not None else {}
    208 
--> 209         self.credentials.before_request(self._request, method, uri, request_headers)
    210 
    211         # Check if the body is a file-like stream, and if so, save the body

~\anaconda3\lib\site-packages\google\auth\credentials.py in before_request(self, request, method, url, headers)
    131         # the http request.)
    132         if not self.valid:
--> 133             self.refresh(request)
    134         self.apply(headers)
    135 

~\anaconda3\lib\site-packages\google\oauth2\credentials.py in refresh(self, request)
    308             scopes=scopes,
    309             rapt_token=self._rapt_token,
--> 310             enable_reauth_refresh=self._enable_reauth_refresh,
    311         )
    312 

~\anaconda3\lib\site-packages\google\oauth2\reauth.py in refresh_grant(request, token_uri, refresh_token, client_id, client_secret, scopes, rapt_token, enable_reauth_refresh)
    345 
    346     if not response_status_ok:
--> 347         _client._handle_error_response(response_data)
    348     return _client._handle_refresh_grant_response(response_data, refresh_token) + (
    349         rapt_token,

~\anaconda3\lib\site-packages\google\oauth2\_client.py in _handle_error_response(response_data)
     58         error_details = json.dumps(response_data)
     59 
---> 60     raise exceptions.RefreshError(error_details, response_data)
     61 
     62 

RefreshError: ('invalid_scope: Bad Request', {'error': 'invalid_scope', 'error_description': 'Bad Request'})


Can you help me ?
