### ISSUE TITLE
Local App deployment package dependencies on Windows

### ISSUE THREAD

**Issue by KMarkert** [google/earthengine-api#29]
I am trying to develop an EE application on a windows machine within an Anaconda virtual environment and keep running into an error: CryptoUnavailableError: No crypto library available. I have all of the needed cryptography packages installed. See attached log file. 

Anyway to help get around this error. Is will be best to have a conda-forge recipe created to easily install the EE Ptyhon-API and all of the dependencies.

[app.log](https://github.com/google/earthengine-api/files/1556874/app.log)

**Comment by tylere** [comment]
Could you detail the exact steps you are using to install EE using Anaconda and Windows so that others can try to reproduce your issue?

**Comment by tylere** [comment]
Closing do to lack of discussion.
