### ISSUE TITLE
ee.data.send_ blocks UI thread

### ISSUE THREAD

**Issue by veeprox** [google/earthengine-api#3]
Hi There,

Can anyone comment on the possibility of making the API call to `getInfo()` asynchronous so it doesn't block the main UI thread? I work for a Google Maps partner in Australia and we're working on a project that is processing some NDVI imagery for farms. 

Consider the following call where the call to `get('NDVI_min')` returns a `ComputedObject`

```javascript
//Retrieve the min/max numbers to use when applying the palette stretch
var min_NDVI_num = minmax_NDVI.get('NDVI_min').getInfo();
```

Under the hood the `getInfo()` function executes `xhr.open()` with the following parameters

![offending_line](https://cloud.githubusercontent.com/assets/8123756/10065968/dacf73ec-62bf-11e5-91e2-29aa18417258.jpg)

The issue is that this blocks the UI thread completely, so even though i've popped up a loading dialog here by running my earth engine code in a  `setTimeout(function(){})` the user has to sit a wait with a completely locked browser, which isn't really a nice experience. It also raises a serious looking warning in chrome - see below;

![synchronous api call](https://cloud.githubusercontent.com/assets/8123756/10066174/badeba86-62c2-11e5-9bdb-50001678db58.jpg)

My question is related to how we can potentially move this call to another thread (WebWorker?) or make the call asynchronous using some kind of promise pattern (Q.js or similar). While the API is working fine from a functionality point of view this really does impact usability from the farmer's point of view, especially given connections in remote areas are patchy at best and download speeds are slow.

Thanks for your time.

**Comment by gorelick** [comment]
getInfo takes a callback argument for the purposes of calling
asynchronously.

When the callback is specified, it goes through a different path and issues
an async xhr.
