### ISSUE TITLE
File (Google Drive) not found with 'export-to-drive' demo, development server

### ISSUE THREAD

**Issue by thanhgis** [google/earthengine-api#35]
I cannot go to final output with this error: 
INFO     2018-03-14 06:58:17,512 server.py:239] Sent to client: {"error": "Failed to give file to user: <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files/15wfcU1PJOjAXFwMn-ihj8aKZ4ZW7Zck9/copy?alt=json returned \"File not found: 15wfcU1PJOjAXFwMn-ihj8aKZ4ZW7Zck9\">"}

From my understand, it might be something wrong with _GiveFilesToUser function, but I don't know how to fix/solve. 

Could you please help. 

Thanks in advance

**Comment by tylere** [comment]
Could you give more context about how you arrived at this error? For example, what code did you install? How did you trigger this error?

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
