### ISSUE TITLE
collectionList.size().getInfo() exception

### ISSUE THREAD

**Issue by lorenzori** [google/earthengine-api#38]
when I check for the size of my `collectionList` with `collectionList.size().getInfo()`, if the list is empty I get the following exception:
```
raise ee_exception.EEException(json_content['error']['message'])
ee.ee_exception.EEException: Collection.toList: The value of 'count' must be positive. Got: 0.
```
The way I go around this is to try and catch the exception with ` except ee.ee_exception.EEException:`, however this doesn't seem to work. Any advise? My collection list is from:

```
sentinel = ee.ImageCollection('COPERNICUS/S2') \
                        .filterDate(start_date, end_date) \
                        .select('B2', 'B3', 'B4') \
                        .filterBounds(geojson) \
                        .filterMetadata('CLOUDY_PIXEL_PERCENTAGE', 'less_than', cloud_cover) \
                        .sort('GENERATION_TIME') \
                        .sort('CLOUDY_PIXEL_PERCENTAGE', False) 

collectionList = sentinel.toList(sentinel.size())
```

**Comment by poolkit** [comment]
It means that the is no image for that particular search filter. Try changing the filters and expanding the date range.
