### ISSUE TITLE
Building datalab-ee docker

### ISSUE THREAD

**Issue by guy1ziv2** [google/earthengine-api#39]
I tried build the docker but it reports an error (missing 'gcc' for some reason).  I copy below the build log 

Sending build context to Docker daemon  5.632kB

Step 1/12 : FROM gcr.io/cloud-datalab/datalab:latest
 ---> 2fd17200507a
Step 2/12 : MAINTAINER Guy Ziv <guy1ziv2@gmail.com>
 ---> Using cache
 ---> bca14fe11280
Step 3/12 : RUN apt-get update   && apt-get install -y build-essential libssl-dev libffi-dev   && pip install cryptography   && apt-get purge -y build-essential libssl-dev libffi-dev                       dpkg-dev fakeroot libfakeroot:amd64   && apt-get autoremove -y   && apt-get clean   && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> fbbb20dda56a
Step 4/12 : RUN pip install ipyleaflet   && jupyter nbextension enable --py --sys-prefix ipyleaflet   && pip install notebook==4.4.1
 ---> Running in 524163368f5d
Collecting ipyleaflet
  Downloading https://files.pythonhosted.org/packages/38/b3/4b4833102a6d64b1bdd464b6e3cf9d8f9bf5471c1e7ca6c47a6b63597457/ipyleaflet-0.8.1-py2.py3-none-any.whl (778kB)
Collecting ipywidgets<8,>=7.0.0 (from ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/7d/24/fabc09ad81c6071159a4d12d5bfbddcbea69bd9e3b16c3250ef300c0285f/ipywidgets-7.2.1-py2.py3-none-any.whl (106kB)
Collecting ipython<6.0.0,>=4.0.0; python_version < "3.3" (from ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/52/19/aadde98d6bde1667d0bf431fb2d22451f880aaa373e0a241c7e7cb5815a0/ipython-5.7.0-py2-none-any.whl (760kB)
Collecting nbformat>=4.2.0 (from ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/da/27/9a654d2b6cc1eaa517d1c5a4405166c7f6d72f04f6e7eea41855fe808a46/nbformat-4.4.0-py2.py3-none-any.whl (155kB)
Collecting ipykernel>=4.5.1 (from ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/8e/65/c7ca3e3d05f9bd51b3010076b84f4e7304b12d0abf62a48f6cec2c90c019/ipykernel-4.8.2-py2-none-any.whl (108kB)
Collecting widgetsnbextension~=3.2.0 (from ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/ff/fa/64acc09fc845a6b2dc0724d6f3f81e829b778ed5e9a7559567b4f19a3f4b/widgetsnbextension-3.2.1-py2.py3-none-any.whl (2.2MB)
Collecting traitlets>=4.3.1 (from ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl (74kB)
Collecting pathlib2; python_version == "2.7" or python_version == "3.3" (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/66/a7/9f8d84f31728d78beade9b1271ccbfb290c41c1e4dc13dbd4997ad594dcd/pathlib2-2.3.2-py2.py3-none-any.whl
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/7d/cd/1750d6c35fe86d35f8562091737907f234b78fdffab42b29c72b1dd861f4/backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/3d/57/4d9c9e3ae9a255cd4e1106bb57e24056d3d0709fc01b2e3e345898e49d5b/simplegeneric-0.8.1.zip
Collecting decorator (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Collecting pygments (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl (841kB)
Collecting pexpect; sys_platform != "win32" (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/b9/3c/e51a76fe78a877afd9acd95a51e3b7610c0983b19ef5a5dfa11735a619b8/pexpect-4.5.0-py2.py3-none-any.whl (57kB)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python2.7/site-packages (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets<8,>=7.0.0->ipyleaflet) (39.1.0)
Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/d1/b0/1a6c262da35c779dd79550137aa7c298a424987240a28792ec5ccf48f848/prompt_toolkit-1.0.15-py2-none-any.whl (247kB)
Collecting pickleshare (from ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/9f/17/daa142fc9be6b76f26f24eeeb9a138940671490b91cb5587393f297c8317/pickleshare-0.7.4-py2.py3-none-any.whl
Collecting jsonschema!=2.5.0,>=2.4 (from nbformat>=4.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting ipython-genutils (from nbformat>=4.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting jupyter-core (from nbformat>=4.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/1d/44/065d2d7bae7bebc06f1dd70d23c36da8c50c0f08b4236716743d706762a8/jupyter_core-4.4.0-py2.py3-none-any.whl (126kB)
Collecting tornado>=4.0 (from ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/cf/d1/3be271ae5eba9fb59df63c9891fdc7d8044b999e8ac145994cdbfd2ae66a/tornado-5.0.2.tar.gz (506kB)
Collecting jupyter-client (from ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/94/dd/fe6c4d683b09eb05342bd2816b7779663f71762b4fa9c2d5203d35d17354/jupyter_client-5.2.3-py2.py3-none-any.whl (89kB)
Collecting notebook>=4.4.1 (from widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/c0/66/cfed59f574d03ca5f1b7c5281485a9cc9a0f21342d24e0f057572316dae5/notebook-5.5.0-py2.py3-none-any.whl (8.4MB)
Requirement already satisfied: enum34; python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from traitlets>=4.3.1->ipywidgets<8,>=7.0.0->ipyleaflet) (1.1.6)
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from traitlets>=4.3.1->ipywidgets<8,>=7.0.0->ipyleaflet) (1.11.0)
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/13/bb/e541b74230bbf7a20a3949a2ee6631be299378a784f5445aa5d0047c192b/scandir-1.7.tar.gz
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/ff/4e/fa4a73ccfefe2b37d7b6898329e7dbcd1ac846ba3a3b26b294a78a3eb997/ptyprocess-0.5.2-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython<6.0.0,>=4.0.0; python_version < "3.3"->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting functools32; python_version == "2.7" (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/c5/60/6ac26ad05857c601308d8fb9e87fa36d0ebf889423f47c3502ef034365db/functools32-3.2.3-2.tar.gz
Requirement already satisfied: futures in /usr/local/lib/python2.7/site-packages (from tornado>=4.0->ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->ipyleaflet) (3.2.0)
Collecting singledispatch (from tornado>=4.0->ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/c5/10/369f50bcd4621b263927b0a1519987a04383d4a98fb10438042ad410cf88/singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting backports_abc>=0.4 (from tornado>=4.0->ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/7d/56/6f3ac1b816d0cd8994e83d0c4e55bc64567532f7dc543378bd87f81cebc7/backports_abc-0.5-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from jupyter-client->ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl (211kB)
Collecting pyzmq>=13 (from jupyter-client->ipykernel>=4.5.1->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/5d/b0/3aea046f5519e2e059a225e8c924f897846b608793f890be987d07858b7c/pyzmq-17.0.0-cp27-cp27mu-manylinux1_x86_64.whl (3.0MB)
Collecting nbconvert (from notebook>=4.4.1->widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/39/ea/280d6c0d92f8e3ca15fd798bbcc2ea141489f9539de7133d8fe10ea4b049/nbconvert-5.3.1-py2.py3-none-any.whl (387kB)
Collecting jinja2 (from notebook>=4.4.1->widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl (126kB)
Collecting Send2Trash (from notebook>=4.4.1->widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/13/2e/ea40de0304bb1dc4eb309de90aeec39871b9b7c4bd30f1a3cdcb3496f5c0/Send2Trash-1.5.0.tar.gz
Collecting terminado>=0.8.1 (from notebook>=4.4.1->widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/2e/20/a26211a24425923d46e1213b376a6ee60dc30bcdf1b0c345e2c3769deb1c/terminado-0.8.1-py2.py3-none-any.whl
Collecting entrypoints>=0.2.2 (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/cc/8b/4eefa9b47f1910b3d2081da67726b066e379b04ca897acfe9f92bac56147/entrypoints-0.2.3-py2.py3-none-any.whl
Collecting mistune>=0.7.4 (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/c8/8c/87f4d359438ba0321a2ae91936030110bfcc62fef752656321a72b8c1af9/mistune-0.8.3-py2.py3-none-any.whl
Collecting bleach (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/30/b6/a8cffbb9ab4b62b557c22703163735210e9cd857d533740c64e1467d228e/bleach-2.1.3-py2.py3-none-any.whl
Collecting pandocfilters>=1.4.1 (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/4c/ea/236e2584af67bb6df960832731a6e5325fd4441de001767da328c33368ce/pandocfilters-1.4.2.tar.gz
Collecting testpath (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/15/19/d7bc380c479a184e4a5a9ce516e4e2a773165f89b445f7cdced83d94de25/testpath-0.3.1-py2.py3-none-any.whl (161kB)
Collecting MarkupSafe>=0.23 (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz
Collecting configparser>=3.5; python_version == "2.7" (from entrypoints>=0.2.2->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz
Collecting html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl (117kB)
Collecting webencodings (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.2.0->ipywidgets<8,>=7.0.0->ipyleaflet)
  Downloading https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Building wheels for collected packages: simplegeneric, tornado, scandir, functools32, Send2Trash, pandocfilters, MarkupSafe, configparser
  Running setup.py bdist_wheel for simplegeneric: started
  Running setup.py bdist_wheel for simplegeneric: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/a9/28/53/f24776b4c5bcbe91aaf1f1e247bd6fadd17191aa12fac63902
  Running setup.py bdist_wheel for tornado: started
  Running setup.py bdist_wheel for tornado: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/29/8c/cf/6a5a8f6e35d877c0cb72b109d21c34981504897ce9a605e599
  Running setup.py bdist_wheel for scandir: started
  Running setup.py bdist_wheel for scandir: finished with status 'error'
  Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-PXm5z6/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-iCbQRd --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying scandir.py -> build/lib.linux-x86_64-2.7
  running build_ext
  building '_scandir' extension
  creating build/temp.linux-x86_64-2.7
  gcc -pthread -B /usr/local/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python2.7 -c _scandir.c -o build/temp.linux-x86_64-2.7/_scandir.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
[91m  Failed building wheel for scandir
[0m  Running setup.py clean for scandir
  Running setup.py bdist_wheel for functools32: started
  Running setup.py bdist_wheel for functools32: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/b5/18/32/77a1030457155606ba5e3ec3a8a57132b1a04b1c4f765177b2
  Running setup.py bdist_wheel for Send2Trash: started
  Running setup.py bdist_wheel for Send2Trash: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/f1/ca/e5/bdd5eae705cf50a483257e6ff9dd34911dda3570f0e1340dda
  Running setup.py bdist_wheel for pandocfilters: started
  Running setup.py bdist_wheel for pandocfilters: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/39/01/56/f1b08a6275acc59e846fa4c1e1b65dbc1919f20157d9e66c20
  Running setup.py bdist_wheel for MarkupSafe: started
  Running setup.py bdist_wheel for MarkupSafe: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/33/56/20/ebe49a5c612fffe1c5a632146b16596f9e64676768661e4e46
  Running setup.py bdist_wheel for configparser: started
  Running setup.py bdist_wheel for configparser: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/a3/61/79/424ef897a2f3b14684a7de5d89e8600b460b89663e6ce9d17c
Successfully built simplegeneric tornado functools32 Send2Trash pandocfilters MarkupSafe configparser
Failed to build scandir
Installing collected packages: scandir, pathlib2, backports.shutil-get-terminal-size, simplegeneric, decorator, pygments, ptyprocess, pexpect, wcwidth, prompt-toolkit, pickleshare, ipython-genutils, traitlets, ipython, functools32, jsonschema, jupyter-core, nbformat, singledispatch, backports-abc, tornado, python-dateutil, pyzmq, jupyter-client, ipykernel, configparser, entrypoints, mistune, webencodings, html5lib, bleach, MarkupSafe, jinja2, pandocfilters, testpath, nbconvert, Send2Trash, terminado, notebook, widgetsnbextension, ipywidgets, ipyleaflet
  Running setup.py install for scandir: started
    Running setup.py install for scandir: finished with status 'error'
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-PXm5z6/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-sOyEqA/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying scandir.py -> build/lib.linux-x86_64-2.7
    running build_ext
    building '_scandir' extension
    creating build/temp.linux-x86_64-2.7
    gcc -pthread -B /usr/local/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python2.7 -c _scandir.c -o build/temp.linux-x86_64-2.7/_scandir.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
[91mCommand "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-PXm5z6/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-sOyEqA/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-PXm5z6/scandir/
[0mThe command '/bin/bash -c pip install ipyleaflet   && jupyter nbextension enable --py --sys-prefix ipyleaflet   && pip install notebook==4.4.1' returned a non-zero code: 1

**Comment by tylere** [comment]
My guess is that the base image (gcr.io/cloud-datalab/datalab:latest) does not include one or more of the dependencies (gcc) needed by one of the packages you are trying to install. You may have an easier time if you use a base image maintained by the Jupyter project (https://github.com/jupyter/docker-stacks) or the Earth Engine Jupyter Contribution repo (https://github.com/gee-community/ee-jupyter-contrib)

If you want to specifically use Datalab, could you include the Dockerfile (and any other configuration files) and the command you are using to build the Docker image, so that it is easy for others to replicate your error?

**Comment by guy1ziv2** [comment]
I was using a clone of the datalab-ee Dockerfile - nothing else. Because I have no docker on my machine, I used GCP shell VM to try make it.

While I like Jupyter interface, it is no where as easy to setup (for non-experts) as datalab. ... unless there is a way to create a Docker based on Jupyter that one can give to 'datalab create' and it just works?

**Comment by tylere** [comment]
The output was not produced by a direct clone of the datalab-ee Dockerfile. At a minimum, Step 2 was modified:
`Step 2/12 : MAINTAINER Guy Ziv guy1ziv2@gmail.com`
If you provide a copy of the Dockerfile you are using, it makes it easier for others to replicate exactly what you are experiencing.

If you have Docker running locally on your machine, starting up a JupyterLab server can be a two-command process (build and run) as described on this page: https://github.com/gee-community/ee-jupyter-contrib/tree/master/docker/jupyter-scipy-notebook-ee

**Comment by guy1ziv2** [comment]
Okay - I followed another online tutorial, which explained you need to create a new firewall rule for tcp:8888 in the GCP machine. I can not connect to the Jupyter running as a docker on a VM from my local machine. However when it starts it reports some build problems which then fail to resolve -

W 17:27:48.727 LabApp] Build recommended
[W 17:27:48.728 LabApp] @jupyterlab/hub-extension needs to be included in build
[W 17:27:48.728 LabApp] jupyter-leaflet needs to be included in build
[W 17:27:48.728 LabApp] bqplot needs to be included in build
[W 17:27:48.729 LabApp] @jupyter-widgets/jupyterlab-manager needs to be included in build
[W 17:27:48.729 LabApp] @jupyterlab/vega3-extension needs to be included in build
[W 17:27:59.125 LabApp] Build failed, running a clean and rebuild
[W 17:27:59.165 LabApp] 500 POST /lab/api/build?1527442075358 (82.28.201.234): [Errno 13] Permission denied: '.yarn
rc'
[W 17:27:59.166 LabApp] [Errno 13] Permission denied: '.yarnrc'

Any ideas?

**Comment by guy1ziv2** [comment]
These errors are weird - those packages / extentions are part of the Dockerfile... I rebuilt the docker (w/o making any changes to it). Attached is the log from docker build. Any ideas why these extentions are not working properly?
[log (1).txt](https://github.com/google/earthengine-api/files/2046245/log.1.txt)

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
