### ISSUE TITLE
Is there a plan to support Python3？

### ISSUE THREAD

**Issue by cycleuser** [google/earthengine-api#4]
Due to the urllib2 is not available any more in Python3, there are a ImportError: No module named 'urllib2' .

But the installation on Python3 can be done perfectly.

So , as the title, is there a plan to support Python3？

**Comment by max99x** [comment]
You could try using [2to3](https://docs.python.org/2/library/2to3.html) to convert it automatically.

**Comment by cycleuser** [comment]
OK， Thanks， Let me try latter.
