### ISSUE TITLE
Feature request: skew and kurtosis reducers

### ISSUE THREAD

**Issue by vlandau** [google/earthengine-api#40]
Skew and kurtosis reducers would be very valuable, especially for reduceNeighborhood. Doing the calculation the long way (image.neighborhoodToArray(), then calculating, etc.) would be quite time consuming and messy, so a shortcut would be great! Thanks!

**Comment by tylere** [comment]
Thanks for the feature request. I have added this as a feature request for the Earth Engine backend codebase.

**Comment by vlandau** [comment]
It appears that these reducers have been added, so going to close this issue. Thanks!
