### ISSUE TITLE
Feature request: "priority" parameter for export functions

### ISSUE THREAD

**Issue by cgmorton** [google/earthengine-api#41]
Quite often I have quite a few low priority export tasks queued up, but then I have one new export that I would like to have run right away.  I was hoping you might consider adding some sort of "priority" parameter to the export functions so that I can modify the execution order of my own tasks.

**Comment by allredbw** [comment]
+1. I've also thought of having a "short" and "long" queue. Tasks in the short queue automatically get cancelled after a specified time period of running, maybe one or two hours. Tasks in the longer queue run until finished.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
