### ISSUE TITLE
python3.6 installation:OSError: [Errno 65] No route to host

### ISSUE THREAD

**Issue by kwanxiang** [google/earthengine-api#42]
I follow this page(https://developers.google.com/earth-engine/python_install_manual) to install API, everything was going well, but when I tested the installation, I got this error after I input: ee.Initialize().my computer connected to google properly.my os is Mac os 10.11.6. please help me with this, thanks a lot.

**Comment by tylere** [comment]
Can you include the exact error message you are receiving when running ee.Initialize() ?

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
