### ISSUE TITLE
google-api-python-client dropped support for oauth2client

### ISSUE THREAD

**Issue by exequiel09** [google/earthengine-api#44]
Version 1.7.0 of [`google-api-python-client` recently dropped oauth2client](https://github.com/google/google-api-python-client/pull/499) as dependency which breaks this API library for EE. This is due to `oauth2client` is deprecated. See https://github.com/google/oauth2client

Affected Files / Lines:

https://github.com/google/earthengine-api/blob/e6fc9f3a30aee127611ce2fe62483cb5d4368650/python/ee/_helpers.py#L20-L21

**Comment by francbartoli** [comment]
Same error here within an environment based on py3

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
