### ISSUE TITLE
Service account authentication leads to error 404

### ISSUE THREAD

**Issue by m-mohr** [google/earthengine-api#45]
I just tried to set up a bare-bone GEE project using the JavaScript library. I installed the dependencies with NPM and executes the following script (service.js) by calling `node service.js`:
```
const ee = require('@google/earthengine');
const privateKey = require('./pkey.json');

const runAnalysis = () => {
  ee.initialize();
  const image = new ee.Image('srtm90_v4');
  image.getMap({min: 0, max: 1000}, (map) => {
	  console.log(map);
  });
};

ee.data.authenticateViaPrivateKey(privateKey, runAnalysis, (e) => {
  console.error('Authentication error: ' + e);
});
```

I get the following error:
```
c:\Dev\gee-test\node_modules\@google\earthengine\build\main.js:13389
          throw ee.initializationFailure_(e), e;
          ^

Error: Server returned HTTP code: 404
    at Object.ee.data.handleResponse_ (c:\Dev\gee-test\node_modules\@google\earthengine\build\main.js:10785:9)
    at Object.ee.data.send_ (c:\Dev\gee-test\node_modules\@google\earthengine\build\main.js:10734:18)
    at Object.ee.data.getAlgorithms (c:\Dev\gee-test\node_modules\@google\earthengine\build\main.js:10437:24)
    at Function.ee.ApiFunction.initialize (c:\Dev\gee-test\node_modules\@google\earthengine\build\main.js:12074:78)
    at Object.ee.initialize (c:\Dev\gee-test\node_modules\@google\earthengine\build\main.js:13387:26)
    at runAnalysis (c:\Dev\gee-test\service.js:7:6)
    at Object.ee.data.handleAuthResult_ (c:\Dev\gee-test\node_modules\@google\earthengine\build\main.js:10815:16)
    at c:\Dev\gee-test\node_modules\@google\earthengine\build\main.js:10387:103
    at c:\Dev\gee-test\node_modules\@google\earthengine\build\main.js:10363:41
    at c:\Dev\gee-test\node_modules\google-auth-library\lib\auth\jwtclient.js:119:5
```

What's the problem here?

Tested with the all versions starting from 0.1.136-prerelease up to 0.1.140-prerelease. It is working flawlessly with OAuth authentication. I am pretty sure the service account authentication using the same private key worked earlier this year, but I can't get it running again. Could it be that my service account is not valid any longer? But in this case I'd except an authentication error with a status code of either 401 or 403 and not 404.

Thank you!

**Comment by m-mohr** [comment]
I debugged this a little more and tried to find a difference between both authentication it seems like the requests to GEE are the same, except the Bearer token. The service account based token leads to a rejection with error 404, the other authentication method receives a proper response. That was reason enough to contact my contact person at Google and let them verify my service account. The account wasn't in the authorization group anymore for whatever reason. It was added to the group again and it is working again. So that was some kind of bug outside of the library itself. => Closing this issue, thanks.

**Comment by malpaniHMC** [comment]
Hey! I'm having similar problems. OAuth works fine. But I'm trying to use a Google cloud function and need to create a service account. Here is the error that I'm getting: 
`Traceback (most recent call last):
  File "earthEngine.py", line 11, in <module>
    ee.Initialize(credentials)
  File "//anaconda3/envs/CS121/lib/python3.7/site-packages/ee/__init__.py", line 123, in Initialize
    ApiFunction.initialize()
  File "//anaconda3/envs/CS121/lib/python3.7/site-packages/ee/apifunction.py", line 154, in initialize
    signatures = data.getAlgorithms()
  File "//anaconda3/envs/CS121/lib/python3.7/site-packages/ee/data.py", line 943, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "//anaconda3/envs/CS121/lib/python3.7/site-packages/ee/data.py", line 1788, in send_
    'Server returned HTTP code: %d' % response.status)
ee.ee_exception.EEException: Server returned HTTP code: 404`

I'm following instructions on this page: https://developers.google.com/earth-engine/service_account 

Please let me know if there's anything I can do!

**Comment by donmccurdy** [comment]
@malpaniHMC I believe the problem you're describing is different from this one. Could you reopen https://github.com/google/earthengine-api/issues/45 if you're still having issues? In particular, you'll need to request access for your service account, and that probably hasn't been granted yet if it was created earlier today.

**Comment by malpaniHMC** [comment]
@donmccurdy  That could be true. I filled that Google form for my service account today itself. How will I know if its been granted? I assume this is different from my account being authorized for using the API?

**Comment by gino-m** [comment]
Service account requests can take up to 72 hours to be process. Once
completed, you will receive an email confirming your account has been
activated. Thanks for your patience!

**Comment by ranjangiet** [comment]
> I debugged this a little more and tried to find a difference between both authentication methods. It seems like the requests to GEE are the same, except the Bearer token. The service account based token leads to a rejection with error 404, which sounds like a mistake and should be 403. The other authentication method receives a proper response. That was reason enough to contact my contact person at Google and let them verify my service account. The account wasn't in the authorization group anymore for whatever reason. It was added to the group again and it is working again. So that was some kind of bug outside of the library itself. => Closing this issue. Sorry for any inconvenience.

what is the contact emailid to add service account in the group ?
