### ISSUE TITLE
Reducers missing

### ISSUE THREAD

**Issue by m-mohr** [google/earthengine-api#46]
Maybe I am missing something, but it seems that the reducers (e.g. `ee.Reducer.min()`) are missing in the libraries. I am trying to use the `ee.Image.reduceRegions()` method, but can't get it working due to the missing reducers. How to solve that?

**Comment by gorelick** [comment]
You probably haven't called initialize().  Most of the library is built on
the fly during initialization.

**Comment by m-mohr** [comment]
Yes, indeed. Thanks.
