### ISSUE TITLE
Support oauth2client >= 2.0 for service accounts

### ISSUE THREAD

**Issue by cgmorton** [google/earthengine-api#5]
The function _oauth2client.client.SignedJwtAssertionCredentials()_ (called in ServiceAccountCredentials() in ee/_helper.py) was removed in versions >=2.0 of oauth2client ([changelog](https://github.com/google/oauth2client/blob/master/CHANGELOG.md#special-note-about-serviceaccountcredentials)).  This causes the the following exception to be raised when trying to initialize EE with service account credentials using newer versions of oauth2client:

```
return oauth2client.client.SignedJwtAssertionCredentials(
AttributeError: 'module' object has no attribute 'SignedJwtAssertionCredentials'
```

Typically I roll back oauth2client to 1.5.2, but other modules (like [gcloud](https://github.com/GoogleCloudPlatform/gcloud-python)) rely on the newer version of oauth2client, which makes it difficult to use both modules in the app.

**Comment by yogesh4mantlelabs** [comment]
Initially i was using earthengine-api-0.1.87 (note that I am using windows) and oauth2client<2. 
I got following error:
Traceback (most recent call last):
File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google
_appengine\google\appengine\runtime\wsgi.py", line 240, in Handle
handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google
_appengine\google\appengine\runtime\wsgi.py", line 299, in _LoadHandler
handler, path, err = LoadObject(self._handler)
File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google
_appengine\google\appengine\runtime\wsgi.py", line 85, in LoadObject
obj = __import__(path[0])
File "E:\googleearth\sample\crop_earthengine\demos\trendy-lights\server.py", l
ine 226, in 
config.EE_ACCOUNT, config.EE_PRIVATE_KEY_FILE)
INFO 2016-07-16 11:16:36,957 module.py:788] default: "GET / HTTP/1.1" 500 -
INFO 2016-07-16 11:16:36,957 module.py:788] default: "GET / HTTP/1.1" 500 -
File "E:\googleearth\sample\crop_earthengine\demos\trendy-lights\lib\ee__init
.py", line 182, in ServiceAccountCredentials
email, key_data, oauth.SCOPE)
File "E:\googleearth\sample\crop_earthengine\demos\trendy-lights\lib\oauth2cli
ent\util.py", line 140, in positional_wrapper
return wrapped(args, *kwargs)
File "E:\googleearth\sample\crop_earthengine\demos\trendy-lights\lib\oauth2cli
ent\client.py", line 1630, in __init
_RequireCryptoOrDie()
File "E:\googleearth\sample\crop_earthengine\demos\trendy-lights\lib\oauth2cli
ent\client.py", line 1581, in _RequireCryptoOrDie
raise CryptoUnavailableError('No crypto library available')
CryptoUnavailableError: No crypto library available

To remove this error, i had tried installing pycrypto again, also i have cross checked with app.yaml for libraries but error remains as it is.

**Comment by cgmorton** [comment]
Have to posted your question/problem to the Google Earth Engine Developer group page?  You are much more likely to get a response there, and there are lots of older discussions you can look/search through for ideas.  
Also, try installing the cryptography module (and maybe pyopenssl) instead of pycrypto.

**Comment by jonas-eberle** [comment]
Hi, I discovered the same issue and wrote a workaround in my application based on the issue #401 you have referenced. 

Instead of calling 
`authorization = ee.ServiceAccountCredentials(MY_SERVICE_ACCOUNT, MY_PRIVATE_KEY_FILE)`
`ee.Initialize(authorization)`

you can use the following
`from oauth2client.service_account import ServiceAccountCredentials`
`from ee import oauth`
`authorization = ServiceAccountCredentials.from_p12_keyfile(MY_SERVICE_ACCOUNT, MY_PRIVATE_KEY_FILE, scopes=oauth.SCOPE)`
`ee.Initialize(authorization)`

**Comment by Majkiboy** [comment]
Hi! I'm facing the same problem, I have tried both the "trendy lights" and the "server-auth" examples. The thing is that when I'm trying to change the authentication in the application, I just get a very similar error message. Am I changing in the wrong place?

 File "C:[local folders]~~\ee\_helpers.py", line 65, in ServiceAccountCredentials
    return ServiceAccountCredentials.from_p12_keyfile(
**AttributeError: 'function' object has no attribute 'from_p12_keyfile'**

in _helper.py I find:
```
def ServiceAccountCredentials(email, key_file=None, key_data=None):
  if key_file:
    key_data = open(key_file, 'rb').read()
  return oauth2client.client.SignedJwtAssertionCredentials(
      email, key_data, oauth.SCOPE)
```
I am trying to changed to this
```
def ServiceAccountCredentials(email, key_file=None, key_data=None):
  if key_file:
    key_data = open(key_file, 'rb').read()
  return ServiceAccountCredentials.from_p12_keyfile(
      email, key_data, scopes=oauth.SCOPE)
```

**Comment by jmalczyk** [comment]
Doesn't look like this has been fixed yet in the python client but you can get around it using a json private key instead of p12/pem.  See PR #11 for the server-auth example.

**Comment by tylere** [comment]
Release v0.1.105 added support for oauth2client 2+ and JSON formatted credentials files.
See: https://github.com/google/earthengine-api/commit/1231f1c9b905a07bbd63cbd2ed6263b430e51460#diff-a8ce43775970f11c1abdb99489512c96

**Comment by tylere** [comment]
@cgmorton are you still experiencing this issue, after updating to at least v0.1.105?

**Comment by cgmorton** [comment]
@tylere I switched to the JSON key format and everything has worked fine for awhile (since v0.1.105).  I'm not sure if this is still an issue or not if you use p12/pem keys though.  Feel free to close the issue if you like, or I can.

**Comment by tylere** [comment]
Given that it works with the preferred JSON key format and the current Python API release, I would suggest closing it.
