### ISSUE TITLE
NodeJS authenticate via private key

### ISSUE THREAD

**Issue by felipe78** [google/earthengine-api#50]
Hello, I'm having trouble logging into Earth Engine with my json key using NodeJS. And it does not display any errors.

After the line of code: "ee.data.authenticateViaPrivateKey (PRIVATE_KEY, () => {"

the script simply stops, I believe it's time for ee.initialize ()

Anyone have any idea what might be happening? I need help, please.

**Comment by donmccurdy** [comment]
Hi @felipe78 — are you using a private key from the EEUS sessions last week? Those were sample keys for the workshop, as mentioned toward the end of the slides. You'll need to create your own service account for your projects through the steps here: https://developers.google.com/earth-engine/service_account

**Comment by donmccurdy** [comment]
Could you verified that you've followed the steps under *Register the service account to use Earth Engine* and someone has replied that the service account is whitelisted? Until that happens, you will not be able to use the service account with the Earth Engine API.

**Comment by felipe78** [comment]
I understand, thank you for the help @donmccurdy, I sent the email 2 days ago and I did not have any feedback, they take too long to respond? I'm looking forward to using the API.
