### ISSUE TITLE
import ee in app engine

### ISSUE THREAD

**Issue by billyz313** [google/earthengine-api#56]
Hi Tyler,

I'm having an issue with importing ee when I do either dev_appserver.py $PWD and when i actually deploy the app with gcloud in app engine.  I am doing all of this in the Cloud Shell.  I have no issues if i simply type python and enter the same exact lines of code in there.   When i put it in the python file that app.yaml calls it throws the error:

import ee
ImportError: No module named ee

It's just the sample code below.  Also, my service account is whitelisted.

```
import ee

ee.Initialize()
# Print the information for an image asset.
image = ee.Image('srtm90_v4')
print image.getInfo()
```

is there something i have to do to make ee accessible to the deployment?

**Comment by tylere** [comment]
My guess is that a copy of the `ee` package was not included in the application directory, so it was not included when the application was deployed to App Engine. Third-party libraries (such as `ee`) need to be explicitly included (See App Engine's [Using third-party libraries](https://cloud.google.com/appengine/docs/standard/python/tools/using-libraries-python-27)). The Earth Engine demos typically implement this via a shell script (example: [build.sh](https://github.com/google/earthengine-api/blob/master/demos/server-auth-python/build.sh)).

If that does not help, could you describe the entire set of steps using in the Cloud Shell?

**Comment by billyz313** [comment]
Ahhh, thank you.  I guess I didn't consider that earthengine would be a third-party library.  This solved the problem, thank you for your help!
