### ISSUE TITLE
ee.Reducer.mean()

### ISSUE THREAD

**Issue by gdellomonaco** [google/earthengine-api#57]
When i try to use this "ee.Reducer.mean()" my pyenv say : 
"Undefined variable from import: Reducer"

Somebody know why?

**Comment by fitoprincipe** [comment]
sounds like you did not run `ee.Initialize()`

**Comment by gdellomonaco** [comment]
this is my code:

import ee;
ee.Initialize();
Ndvi_series = ee.ImageCollection("NOAA/CDR/AVHRR/NDVI/V4");
Zone = ee.Geometry.Polygon([[1,1],
                                    [2,2],
                                    [3,3],
                                    [4,4],
                                    [5,5]]);
NDVI = Ndvi_series.filterBounds(Zone).filterDate('2010-01-01', '2018-06-30').select('NDVI');
                
def elaborateNdvi(img): 
    return img.addBands(img.multiply(0.0001).select([0], ['NDVI']));

NDVI = NDVI.map(elaborateNdvi);

from geetools import chart

chart_ts = chart.Image.series(**{
    'imageCollection': NDVI, 
    'region': Zone,
    'scale': 200,
    'bands': 'NDVI',
    'reducer': ee.Reducer.mean()
})

Is This Correct?

**Comment by fitoprincipe** [comment]
As it seems you are using the python API in a Jupyter Notebook, is it right? Well, closing a code line with `;` is a JavaScript syntax, not python

**Comment by gdellomonaco** [comment]
I'm using an eclipse workspace with pydev package installed and a Python 3.7 interpreter.

**Comment by fitoprincipe** [comment]
Another issue is that your collection has no data in the zone you tried to plot. It looks like it is a test zone, am I right? Try to identify an area that has some data. Then you can do something like:

```
import ee
ee.Initialize()
Ndvi_series = ee.ImageCollection("NOAA/CDR/AVHRR/NDVI/V4")#.limit(10)
Zone = ee.Geometry.Point([-72, -42]).buffer(500)  # This is my test zone
NDVI = Ndvi_series.filterBounds(Zone).filterDate('2010-01-01', '2018-06-30').select('NDVI')

def elaborateNdvi(img):
    return img.addBands(img.multiply(0.0001).select([0], ['NDVI']))

NDVI = NDVI.map(elaborateNdvi).limit(10)

from geetools import ui, tools

chart_ts = ui.chart.Image.series(**{
'imageCollection': NDVI,
'region': Zone,
'scale': 200,
'bands': ['NDVI'],
'reducer': ee.Reducer.mean()
})
```

and as you are not in a Juypyter environment (Notebook or Lab), you have to render the chart in a file `chart_ts.render_to_file()` or in a browser `chart_ts.render_in_browser`

**Comment by gdellomonaco** [comment]
the zone is a test zone. Despite eclipse says me "Undefined variable from import: Reducer", the code runs correctly. Thanks for the help.

**Comment by tylere** [comment]
@gdellomonaco is your issue resolved? If so, can we close this issue?
