### ISSUE TITLE
cannot export table and image 

### ISSUE THREAD

**Issue by gracie2017** [google/earthengine-api#59]
Is there a way could export table and image easily? Thanks!

Tried multiple lines to try to export image and table,like below:

ee.batch.Export.table.toDrive({
  collection: stats,
  description:'vectorsToDriveExample',
  fileFormat: 'KML'
});

ee.batch.Export.map.toCloudStorage(
  image= classifiedImage.clip(city),
  description= 'mapToCloudExample',
  bucket= 'gl1',
  maxZoom= 4,
  region= city2
);

**Comment by tylere** [comment]
Could you post a full example (with sample input data), so that someone can reproduce the exact issue?

**Comment by gracie2017** [comment]
Hi Tylere and Donmccurdy, 

I am using python API under Anaconda 3.5.0 and Jupyter Notebook.

The code is as below. My ultimate goal is to loop over around 100,000 cells to get each cells' estimated areas and classified image. Could you plz help see how I could export the calculate area "stats" and the image "classifiedImage" with loops? Currently even single run could not produce exports successfully. I have tried the ee.batch.Export and geetools.batch.Export. Thanks!


import ee;
ee.Initialize();
dmspdata = ee.ImageCollection('NOAA/DMSP-OLS/NIGHTTIME_LIGHTS');
dmsp = dmspdata.filterDate('2013-01-01','2013-12-31').select('stable_lights').median();
chn_city = ee.FeatureCollection('ft:1bU6ajAdTsfv-SgyQJNKgQx7x6IKU0dEBaA3L_3jT');
i = 27969
city = chn_city.filterMetadata('hex', 'equals', i).first();
toa = ee.Image('LANDSAT/LC8_L1T_ANNUAL_TOA/2013'); 
predictor_city = toa.clip(city);
dmsp_city = dmsp.clip(city);
dmsp_perc = dmsp_city.reduceRegion(ee.Reducer.percentile([90]), city, 100)
urb_class = dmsp_city.gte(ee.Number(dmsp_perc.get("stable_lights")));
vectors = urb_class.addBands(dmsp_city).reduceToVectors(
  geometry= city,
  crs= dmsp_city.projection(),
  scale= 100,
  labelProperty= 'class',
  reducer = ee.Reducer.mean()
);

classifier= ee.Classifier.randomForest(
numberOfTrees= 5
);
training = predictor_city.sampleRegions(vectors,['class'],100);
bands = ['B1', 'B2', 'B3', 'B4', 'B5', 'B6'];
trained = classifier.train(training, 'class', bands); 
classifiedImage = predictor_city.select(bands).classify(trained);
urbanAreaSize = classifiedImage.multiply(ee.Image.pixelArea());
stats = urbanAreaSize.reduceRegion(
reducer= ee.Reducer.sum(),
geometry= city,
crs= dmsp_city.projection(),
scale= 100
#'maxPixels': 5e9
);

**Comment by gracie2017** [comment]
And btw 2 other questions: 1. is there any memory limits for exporting large scale of images/tables? Could I directly export to my local drive? 2. Approximately how long does each export take? Thanks a lot!

**Comment by donmccurdy** [comment]
Oops, I saw semicolons and assumed it was JavaScript. I think you still need to call `task.start()`, but I'm not the right person to answer most of this.

> Could I directly export to my local drive? 

No, you need to export to one of the available locations first. See https://developers.google.com/earth-engine/exporting.

> Approximately how long does each export take?

Depends entirely on the size of your data. :)

**Comment by gracie2017** [comment]
Thanks Donmccurdy! Could you please help give some examples of using the batch.export and geetools.export? Thanks!

**Comment by gracie2017** [comment]
Hi tylere, Could you please help give some examples of using the batch.export and geetools.export in the Python API? Sorry that I am in a tight schedule and need urgent help. Thanks!

**Comment by fitoprincipe** [comment]
Hi @gracie2017, have you tried this?

``` python
task = ee.batch.Export.table.toDrive({
collection: stats,
description:'vectorsToDriveExample',
fileFormat: 'KML'
})

task.start()
```

**Comment by fitoprincipe** [comment]
what errors are you getting?? you should provide more information in order to understand what is happening and how can we help you

**Comment by gracie2017** [comment]
I tried the below code and error is like this:
task = ee.batch.Export.table.toDrive({
collection: stats,
description:'vectorsToDriveExample',
fileFormat: 'CSV'
})
task.start()

NameError                                 Traceback (most recent call last)
<ipython-input-2-166ae9bee8ef> in <module>()
      1 task = ee.batch.Export.table.toDrive({
----> 2 collection: stats,
      3 description:'vectorsToDriveExample',
      4 fileFormat: 'CSV'
      5 })

NameError: name 'collection' is not defined

**Comment by fitoprincipe** [comment]
that is a python issue. In python, `dict` keys must be strings or numbers. I updated my previous comment

**Comment by gracie2017** [comment]
The code is running now, and I am waiting for the export results in google drive.
Meanwhile, hi fitoprincipe, 2 questions:
1. could you please help give an example to output the image "classfiedImage"?
2. I need to loop over around 100000 cells of the same process, which format of "stats" do you recommend to save? And how to output such a large set of "stats"? Thanks!

**Comment by fitoprincipe** [comment]
Hi @gracie2017, I don't have much time now, but in about 7 hrs I may have some.

**Comment by gracie2017** [comment]
Great. I will keep posting my questions here, while you could respond when you got some time. Thx.

**Comment by gracie2017** [comment]
From your previous code, there is an error here:
task = ee.batch.Export.table.toDrive({
'collection': stats,
'folder': 'myFolder',
'description':'vectorsToDriveExample',
'fileFormat': 'KML'
})

task.start()

Error: Image.reduceRegion, argument 'geometry': Invalid type. Expected: Geometry. Actual: Feature.

**Comment by fitoprincipe** [comment]
That error can come from any part of your entire code, that is why Tyler asked you to post a full code, or at least a code that represents what you are trying to do

**Comment by gracie2017** [comment]
I have post the full code in the very beginning. Could you plz try it on your end to see how to solve the error? Thx.

**Comment by gracie2017** [comment]
Repost here:

Hi Tylere and Donmccurdy,

I am using python API under Anaconda 3.5.0 and Jupyter Notebook.

The code is as below. My ultimate goal is to loop over around 100,000 cells to get each cells' estimated areas and classified image. Could you plz help see how I could export the calculate area "stats" and the image "classifiedImage" with loops? Currently even single run could not produce exports successfully. I have tried the ee.batch.Export and geetools.batch.Export. Thanks!

import ee;
ee.Initialize();
dmspdata = ee.ImageCollection('NOAA/DMSP-OLS/NIGHTTIME_LIGHTS');
dmsp = dmspdata.filterDate('2013-01-01','2013-12-31').select('stable_lights').median();
chn_city = ee.FeatureCollection('ft:1bU6ajAdTsfv-SgyQJNKgQx7x6IKU0dEBaA3L_3jT');
i = 27969
city = chn_city.filterMetadata('hex', 'equals', i).first();
toa = ee.Image('LANDSAT/LC8_L1T_ANNUAL_TOA/2013');
predictor_city = toa.clip(city);
dmsp_city = dmsp.clip(city);
dmsp_perc = dmsp_city.reduceRegion(ee.Reducer.percentile([90]), city, 100)
urb_class = dmsp_city.gte(ee.Number(dmsp_perc.get("stable_lights")));
vectors = urb_class.addBands(dmsp_city).reduceToVectors(
geometry= city,
crs= dmsp_city.projection(),
scale= 100,
labelProperty= 'class',
reducer = ee.Reducer.mean()
);

classifier= ee.Classifier.randomForest(
numberOfTrees= 5
);
training = predictor_city.sampleRegions(vectors,['class'],100);
bands = ['B1', 'B2', 'B3', 'B4', 'B5', 'B6'];
trained = classifier.train(training, 'class', bands);
classifiedImage = predictor_city.select(bands).classify(trained);
urbanAreaSize = classifiedImage.multiply(ee.Image.pixelArea());
stats = urbanAreaSize.reduceRegion(
reducer= ee.Reducer.sum(),
geometry= city,
crs= dmsp_city.projection(),
scale= 100
#'maxPixels': 5e9
);

**Comment by gracie2017** [comment]
Hi guys, any thoughts?

**Comment by fitoprincipe** [comment]
Haven't tried yet, but probably I'll have an issue accessing the fusion table (permission issue)

**Comment by fitoprincipe** [comment]
First of all, if you are using python, you have to get rid of all closing statements (;).. that is for JavaScript

**Comment by gracie2017** [comment]
I could share the fusion table with you. Could you please let me know your email address? Thanks!

**Comment by gracie2017** [comment]
You are right. since the ; so far did not impacted the code running, could you plz help try running it on your end and let me know your thoughts? Thanks!

**Comment by fitoprincipe** [comment]
Yes, that is what I am trying to do. My email is fitoprincipe82@gmail.com

**Comment by gracie2017** [comment]
Fusion table shared.

**Comment by fitoprincipe** [comment]
``` python
dmspdata = ee.ImageCollection('NOAA/DMSP-OLS/NIGHTTIME_LIGHTS')

dmsp = dmspdata.filterDate('2013-01-01','2013-12-31').select('stable_lights').median()

chn_city = ee.FeatureCollection('ft:1bU6ajAdTsfv-SgyQJNKgQx7x6IKU0dEBaA3L_3jT')

i = 27969

city = chn_city.filterMetadata('hex', 'equals', i).first()

toa = ee.Image('LANDSAT/LC8_L1T_ANNUAL_TOA/2013')

predictor_city = toa.clip(city)

dmsp_city = dmsp.clip(city)
dmsp_perc = dmsp_city.reduceRegion(ee.Reducer.percentile([90]), city.geometry(), 100)
urb_class = dmsp_city.gte(ee.Number(dmsp_perc.get("stable_lights")))

vectors = urb_class.addBands(dmsp_city).reduceToVectors(
    geometry= city.geometry(),
    crs= dmsp_city.projection(),
    scale= 100,
    labelProperty= 'class',
    reducer = ee.Reducer.mean()
)

classifier= ee.Classifier.randomForest(
    numberOfTrees= 5
)

training = predictor_city.sampleRegions(vectors,['class'],100)
bands = ['B1', 'B2', 'B3', 'B4', 'B5', 'B6']
trained = classifier.train(training, 'class', bands)
classifiedImage = predictor_city.select(bands).classify(trained)
urbanAreaSize = classifiedImage.multiply(ee.Image.pixelArea())
stats = urbanAreaSize.reduceRegion(
    reducer= ee.Reducer.sum(),
    geometry= city.geometry(),
    crs= dmsp_city.projection(),
    scale= 100
    #'maxPixels': 5e9
)
```
I can send you the notebook if you want

**Comment by gracie2017** [comment]
Yeah that would be great. Could you send to gracieli2017@outlook.com? Thanks a lot!

**Comment by gena** [comment]
Usually, adding ** before {} dictionary helps, this is a typical error when switching from JavaScript to Python EE API, not sure if EE can be a bit more aggressive checking these errors. Also, you need to wrap key names with quotes:

```
task = ee.batch.Export.table.toDrive(**{
  "collection": stats,
  "description":'vectorsToDriveExample',
  "fileFormat": 'KML'
})

task.start()
```

Or use explicit argument names:

```
task = ee.batch.Export.table.toDrive(
  collection=stats,
  description='vectorsToDriveExample',
  fileFormat='KML'
)

task.start()
```

I'm getting permission denied on the fusion table, so can't test if this works.

**Comment by gracie2017** [comment]
Thanks Gena. Rodrigo has greatly helped me successfully exported the wanted 'stats'. But I still need help on the below:
1. Since I have ~100,000 cells to output, do you know there is some faster way for exporting the table of the series of the 'stats'? 
2. 1.	I would like to output the series of Image 'classifiedImage', which code will you recommend? 
3. 2.	If I would like to download the landsat image collections into my own local drive, do you have recommendations on the download code? 

Could you plz help provide your email address so I could share the table with you? Thanks!

**Comment by gracie2017** [comment]
My email address is gracieli2017@outlook.com You could directly send me an email. Thanks.
