### ISSUE TITLE
The file javascript/build/ee_api_js.js was removed

### ISSUE THREAD

**Issue by gena** [google/earthengine-api#6]
A minified version of the EE JavaScript API (ee_api_js.js) was removed in the latest revision. I reference it directly from the GitHub repository using RawGit (https://rawgit.com/):

`  <script src="https://cdn.rawgit.com/google/earthengine-api/master/javascript/build/ee_api_js.js" </script>
`
But the file ee_api_js.js (and sourcemaps) was removed in the latest release.

**Comment by maxh** [comment]
Thanks for reporting. This will be fixed in this week's .90 release.
