### ISSUE TITLE
Exporting corrupted DMSP 'stable lights' time luminosity image 

### ISSUE THREAD

**Issue by CooperNederhood** [google/earthengine-api#61]
I am using the javascript code editor to export time series of Landsat and night-time luminosity data, one cleaned composite per year from now back to 2000. I export the yearly images to my Google Drive. I have no problem for Landsat 8, Landsat 7, and Sentinel AND for the VIIRS luminosity data. However, when I do this same process for the DMSP "stable_lights" band the exported .tiff file is always corrupted - it's just a tiny file of black and grey checkerboard. The exported DMSP image displays as desired in the viewer and the code runs without issue.

I have tried various years, various export scales, shrank the region of interest, and cleared out my drive to ensure there is adequate space available. Also, I reran code exporting DMSP data from this past spring (which used to work) and now it has the same problem. I am completely at a loss as to what the issue is. Could this be an Earth Engine issue rather than a code issue? Or perhaps there is something obvious I am missing? Example code from Earth Engine Code Editor is immediately below:

```

var DMSPCollection = ee.ImageCollection("NOAA/DMSP-OLS/NIGHTTIME_LIGHTS").select('stable_lights');
var VIIRSCollection = ee.ImageCollection("NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG").select('avg_rad');
var export_geometry = ee.Geometry.Rectangle(3.1091, 6.4136, 3.4, 6.4);

var DMSPParams = {bands: ['stable_lights'], min:0, max:63};
var VIIRSParams = {bands: ['avg_rad']};

var DMSP_2013 = DMSPCollection.filterDate('2013-01-01', '2013-12-31').median();
var DMSP_2009 = DMSPCollection.filterDate('2009-01-01', '2009-12-31').median();


Map.addLayer(DMSP_2013, DMSPParams, "DMSP_2013");
Map.addLayer(DMSP_2009, DMSPParams, "DMSP_2009");


Export.image.toDrive({
  image: DMSP_2013,
  description: 'DMSP_RES30_2013',
  scale: 30,
  region: export_geometry
});

print(DMSP_2009);

Export.image.toDrive({
  image: DMSP_2009,
  description: 'DMSP_RES30_2009',
  scale: 30, 
  region: export_geometry
});

```

**Comment by tylere** [comment]
Your code appears to be working correctly, but you are specifying a small region to export. You can preview the export region by clipping the images to the export geometry:

https://code.earthengine.google.com/e1c0d52b3f071fee644d1156fb810c4c
```
Map.addLayer(DMSP_2013.clip(export_geometry), DMSPParams, "DMSP_2013");
Map.addLayer(DMSP_2009.clip(export_geometry), DMSPParams, "DMSP_2009");
Map.centerObject(export_geometry);
```

Here is a screenshot of the result:

![image](https://user-images.githubusercontent.com/92862/46411854-a85e0a80-c6d1-11e8-959d-619ee69db924.png)

After exporting a GeoTIFF and loading it into QGIS, the results look similar:

![image](https://user-images.githubusercontent.com/92862/46411760-73ea4e80-c6d1-11e8-9867-cb7ce3a3158c.png)

**Comment by CooperNederhood** [comment]
Thanks for the feedback! The small region is just a result of my troubleshooting and for me the problem persists. I'm not getting the same output from exporting the image. My procedure, which I have used for other Earth Engine images without issue is as follows:

**Step 1: Run the above code and run the export task**
![step_1](https://user-images.githubusercontent.com/31707367/46418639-d18e9300-c6f1-11e8-99a0-432c41de26e3.png)


**Step 2: Download to my Google Drive**
![step_2](https://user-images.githubusercontent.com/31707367/46418707-f08d2500-c6f1-11e8-989d-3b9d80262d46.png)


**Step 3: Download to my machine. I need to do some post-processing and sampling so I need it on my local machine. I am often not able to preview tiff files, so I was not surprised by that**
![step_3](https://user-images.githubusercontent.com/31707367/46418766-0c90c680-c6f2-11e8-8efa-d0a2e9222c7a.png)


**Step 4: View the downloaded file - and it looks corrupted?**
![last_step](https://user-images.githubusercontent.com/31707367/46418864-377b1a80-c6f2-11e8-95a2-de9edf3485b1.png)

**Comment by tylere** [comment]
Could you attach the TIFF output file to this issue?

**Comment by CooperNederhood** [comment]
Certainly! I got an error that github doesn't support tif files so I've zipped it. Let me know if you have any issues accessing the file.
[DMSP_RES30_2013(3).tif.zip](https://github.com/google/earthengine-api/files/2444583/DMSP_RES30_2013.3.tif.zip)

**Comment by CooperNederhood** [comment]
Also, I dual boot Windows and Ubuntu on my machine. To troubleshoot I've run the same code using both Windows/Ubuntu and Firefox/Chrome and the problem persists.

**Comment by dhritirajsen** [comment]
Hello, This is issue solved? I am having the similar issue, where the downloaded image doesn't cover my study region

![image](https://user-images.githubusercontent.com/34183400/54668321-965e1000-4b29-11e9-8280-6487a503c1b4.png)

![image](https://user-images.githubusercontent.com/34183400/54668348-a1b13b80-4b29-11e9-98e7-71b5e9b7b0b2.png)

https://code.earthengine.google.com/d280ea4578805749a22d3de69e4a8fef

**Comment by tylere** [comment]
@dhritirajsen could you say more about what you expect that you are not seeing in the downloaded image?  It appears to me that the image actually does cover all of the region shown in the Code Editor, and more.

**Comment by GabiGIS** [comment]
Following the code above in this post, I would like to export to drive VIIRS nightlight data, instead DMSP, I have modified the the following code (bellow) for that,  however does not let me download to drive.
I use an asset I upload which is a polygon I called “export_geometry” but really is not so important for me to crop to polygon borders on the contrary I just need to download an area enough big that includes/cover that polygon, then I can further crop outside GEE, when needed.
Thanks a lot

Code: 

// centre map on AOI
Map.setCenter(35.24, 32.01, 8);

var dataset = ee.ImageCollection('NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG')
                  .filter(ee.Filter.date('2017-07-01', '2017-07-31'));
var nighttime = dataset.select('avg_rad');
var nighttimeVis = {min: 0.0, max: 60.0};

//geometry
var export_geometry = ee.FeatureCollection("users/gabiklm01/poligonOfslopes");

// availability
print(nighttime);

Map.addLayer(nighttime, nighttimeVis, 'Nighttime');
Map.addLayer(export_geometry.draw({color: '006600', strokeWidth: 5}), {}, 'drawn');

// exports 
Export.image.toDrive({
  image: nighttime,
  description: 'VIIRS_RES30_2017',
  scale: 30,
  region: export_geometry
});

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
