### ISSUE TITLE
ConnectionResetError: [WinError 10054]

### ISSUE THREAD

**Issue by gracie2017** [google/earthengine-api#62]
Was going to export tables. The error is as below. Could anyone please help?
Have tried multiple times.Really need the help.
Thanks!
---------------------------------------------------------------------------
ConnectionResetError                      Traceback (most recent call last)
<ipython-input-6-903b654f14b5> in <module>()
      2 #need to change name and descriptions per run
      3 task = ee.batch.Export.table.toDrive(feafea, 'run1-2013-oct2', 'run1-folder', 'run1-2013-oct2', 'csv')
----> 4 task.start()

~\Anaconda\lib\site-packages\ee\batch.py in start(self)
     71       raise ee_exception.EEException(
     72           'Task config must be specified for tasks to be started.')
---> 73     data.startProcessing(self.id, self.config)
     74 
     75   def status(self):

~\Anaconda\lib\site-packages\ee\data.py in startProcessing(taskId, params)
    592   args = params.copy()
    593   args['id'] = taskId
--> 594   return send_('/processingrequest', args)
    595 
    596 

~\Anaconda\lib\site-packages\ee\data.py in send_(path, params, opt_method, opt_raw)
    825     return response, content
    826 
--> 827   response, content = send_with_backoff()
    828 
    829   # Call the profile hook if present. Note that this is done before we handle

~\Anaconda\lib\site-packages\ee\data.py in send_with_backoff(retries)
    816     try:
    817       response, content = http.request(
--> 818           url, method=opt_method, body=payload, headers=headers)
    819       if response.status == 429:
    820         if retries < MAX_RETRIES:

~\Anaconda\lib\site-packages\oauth2client\transport.py in new_request(uri, method, body, headers, redirections, connection_type)
    173         resp, content = request(orig_request_method, uri, method, body,
    174                                 clean_headers(headers),
--> 175                                 redirections, connection_type)
    176 
    177         # A stored token may expire between the time it is retrieved and

~\Anaconda\lib\site-packages\oauth2client\transport.py in request(http, uri, method, body, headers, redirections, connection_type)
    280     return http_callable(uri, method=method, body=body, headers=headers,
    281                          redirections=redirections,
--> 282                          connection_type=connection_type)
    283 
    284 

~\Anaconda\lib\site-packages\httplib2\__init__.py in request(self, uri, method, body, headers, redirections, connection_type)
   1512                     content = b""
   1513                 else:
-> 1514                     (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
   1515         except Exception as e:
   1516             if self.force_exception_to_status_code:

~\Anaconda\lib\site-packages\httplib2\__init__.py in _request(self, conn, host, absolute_uri, request_uri, method, body, headers, redirections, cachekey)
   1262             auth.request(method, request_uri, headers, body)
   1263 
-> 1264         (response, content) = self._conn_request(conn, request_uri, method, body, headers)
   1265 
   1266         if auth:

~\Anaconda\lib\site-packages\httplib2\__init__.py in _conn_request(self, conn, request_uri, method, body, headers)
   1186                 if conn.sock is None:
   1187                     conn.connect()
-> 1188                 conn.request(method, request_uri, body, headers)
   1189             except socket.timeout:
   1190                 conn.close()

~\Anaconda\lib\http\client.py in request(self, method, url, body, headers, encode_chunked)
   1237                 encode_chunked=False):
   1238         """Send a complete request to the server."""
-> 1239         self._send_request(method, url, body, headers, encode_chunked)
   1240 
   1241     def _send_request(self, method, url, body, headers, encode_chunked):

~\Anaconda\lib\http\client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1283             # default charset of iso-8859-1.
   1284             body = _encode(body, 'body')
-> 1285         self.endheaders(body, encode_chunked=encode_chunked)
   1286 
   1287     def getresponse(self):

~\Anaconda\lib\http\client.py in endheaders(self, message_body, encode_chunked)
   1232         else:
   1233             raise CannotSendHeader()
-> 1234         self._send_output(message_body, encode_chunked=encode_chunked)
   1235 
   1236     def request(self, method, url, body=None, headers={}, *,

~\Anaconda\lib\http\client.py in _send_output(self, message_body, encode_chunked)
   1063                     chunk = f'{len(chunk):X}\r\n'.encode('ascii') + chunk \
   1064                         + b'\r\n'
-> 1065                 self.send(chunk)
   1066 
   1067             if encode_chunked and self._http_vsn == 11:

~\Anaconda\lib\http\client.py in send(self, data)
    984             return
    985         try:
--> 986             self.sock.sendall(data)
    987         except TypeError:
    988             if isinstance(data, collections.Iterable):

~\Anaconda\lib\ssl.py in sendall(self, data, flags)
    963             count = 0
    964             while (count < amount):
--> 965                 v = self.send(data[count:])
    966                 count += v
    967         else:

~\Anaconda\lib\ssl.py in send(self, data, flags)
    933                     "non-zero flags not allowed in calls to send() on %s" %
    934                     self.__class__)
--> 935             return self._sslobj.write(data)
    936         else:
    937             return socket.send(self, data, flags)

~\Anaconda\lib\ssl.py in write(self, data)
    634         The 'data' argument must support the buffer interface.
    635         """
--> 636         return self._sslobj.write(data)
    637 
    638     def getpeercert(self, binary_form=False):

ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by parkdino** [comment]
> Could you provide a minimal code example that triggers this behavior, so that others can try to replicate the issue?

`import ee`
`ee.Initialize()`

**Comment by maramir6** [comment]
I had the same issue. There is no reference to the error anywhere in the API documentation. Just an impression that my account had been blocked by the Earth Engine server side.

**Comment by tylere** [comment]
**_Note that in order to be more responsive to bug reports and feature requests, we are transitioning from using GitHub Issues to Google Issue Tracker, which better integrates with the Earth Engine team's software development workflow. Please see the [Get Help](https://developers.google.com/earth-engine/help) page of the Earth Engine documentation for an overview of the recommended communication channels._**

Given that the API changes rapidly, we will need more information in order to help you with your issue. Could open a new [bug report](https://developers.google.com/earth-engine/help#bug-reports) and provide details on:

1. explicit instructions on how you installed the Python API
2. the version of the Python API you are using
3. a copy of the error traceback

Cheers,
Tyler
