### ISSUE TITLE
Node.js TypeError: opt_error is not a function

### ISSUE THREAD

**Issue by giswqs** [google/earthengine-api#63]
@donmccurdy 

I followed the examples on the [slides from EEUS18](http://g.co/earth/eeus2018-nodejs), and I was able to getThumbURL. But I got a 'TypeError: opt_error is not a function' when trying to export the image. Any help will be appreciated!

```
// script.js
var ee = require('@google/earthengine');
var privateKey = require('./privatekey.json');

ee.data.authenticateViaPrivateKey(privateKey);
ee.initialize(null, null, function() {

    // Load a landsat image and select three bands.
  var landsat = new ee.Image('LANDSAT/LC08/C01/T1_TOA/LC08_123032_20140515')

  var url = landsat
.visualize({bands:['B6','B5','B3'], gamma: 1.5})
.getThumbURL({dimensions:'1024x1024', format: 'jpg'});

    console.log(url);
  // Create a geometry representing an export region.
  var geometry = new ee.Geometry.Rectangle([116.2621, 39.8412, 116.4849, 40.01236]);

  var task = ee.batch.Export.image.toDrive({
    image: landsat,
    description: 'imageToDriveExample',
    scale: 30,
    region: geometry
});

  task.start(function(_, error) {
    console.log('Task ' + task.id + ' started.');
});
    
});
```

[user@linux ee-runner]$ node landsat.js
https://earthengine.googleapis.com/api/thumb?thumbid=7617d73d7cedc3bbea3a1b945e18afa6&token=5f615ad0d723fb294badec5b49ce0b57
/media/hdd/Dropbox/git/earth-engine/ee-runner/node_modules/@google/earthengine/build/main.js:10990
        error ? opt_error(error) : opt_success();
                ^

TypeError: opt_error is not a function
    at /media/hdd/Dropbox/git/earth-engine/ee-runner/node_modules/@google/earthengine/build/main.js:10990:17
    at Object.ee.data.handleResponse_ (/media/hdd/Dropbox/git/earth-engine/ee-runner/node_modules/@google/earthengine/build/main.js:9826:12)
    at goog.net.XhrIo.request.callback (/media/hdd/Dropbox/git/earth-engine/ee-runner/node_modules/@google/earthengine/build/main.js:9795:63)
    at goog.net.XhrIo.goog.events.EventTarget.fireListeners (/media/hdd/Dropbox/git/earth-engine/ee-runner/node_modules/@google/earthengine/build/main.js:3501:30)
    at Function.goog.events.EventTarget.dispatchEventInternal_ (/media/hdd/Dropbox/git/earth-engine/ee-runner/node_modules/@google/earthengine/build/main.js:3541:169)
    at goog.net.XhrIo.goog.events.EventTarget.dispatchEvent (/media/hdd/Dropbox/git/earth-engine/ee-runner/node_modules/@google/earthengine/build/main.js:3467:34)
    at goog.net.XhrIo.dispatchErrors_ (/media/hdd/Dropbox/git/earth-engine/ee-runner/node_modules/@google/earthengine/build/main.js:8719:62)
    at goog.net.XhrIo.onReadyStateChangeHelper_ (/media/hdd/Dropbox/git/earth-engine/ee-runner/node_modules/@google/earthengine/build/main.js:8752:263)
    at goog.net.XhrIo.onReadyStateChangeEntryPoint_ (/media/hdd/Dropbox/git/earth-engine/ee-runner/node_modules/@google/earthengine/build/main.js:8738:8)
    at goog.net.XhrIo.onReadyStateChange_ (/media/hdd/Dropbox/git/earth-engine/ee-runner/node_modules/@google/earthengine/build/main.js:8733:12)

**Comment by donmccurdy** [comment]
Hi! I'm crossposting our conversation here for future readers:

My slides contained a typo; the usage of `task.start` should be:

```js
task.start(function() {
  console.log('Task ' + task.id + ' has started.');
}, function(e) {
  console.error(e);
});
```

You'll then see the actual error, rather than the error about `opt_error` not working. I believe the issue with the geometry parameter is a bug. For the moment you can work around it by doing this instead:

region: JSON.stringify( geometry.toGeoJSON() )

Also note you'll need to select bands on the image, e.g. landsat.select(['B4', 'B3', 'B2'])

About the task not appearing in your GEE task list — when using a Service Account for authentication, its exports will not appear in your GEE task list and (unfortunately) I believe the output will be inaccessible in the Service Account's own Drive. Some options to solve this are:

(a) Use OAuth authentication. The @google/earthengine package currently only supports that within a web browser, but ee-runner (which you appear to be also using here already?) provides a way of doing OAuth in Node.js as well. 
(b) Continue using the Service Account, and export to a Cloud Storage bucket instead.

**Comment by giswqs** [comment]
Thanks Don! I am sharing the working version of the script for future readers. I also tried [ee-runner](https://github.com/gee-community/ee-runner). Athough I could not get ee-runner to work with Node.js v10.10.0 due to the [TypeError: cache.get is not a function](https://github.com/gee-community/ee-runner/issues/22), I finally got it to work with Node.js v8.10.0.

```
// script.js
var ee = require('@google/earthengine');
var privateKey = require('./privatekey.json'); 

ee.data.authenticateViaPrivateKey(privateKey);
ee.initialize(null, null, function() {

    // Load a landsat image and select three bands.
  var landsat = new ee.Image('LANDSAT/LC08/C01/T1_TOA/LC08_123032_20140515')
    .select(['B4', 'B3', 'B2']);

  var url = landsat
    .visualize({bands:['B4','B3','B2'], gamma: 1.5})
    .getThumbURL({dimensions:'1024x1024', format: 'jpg'});

    console.log(url);
  // Create a geometry representing an export region.
  var geometry = new ee.Geometry.Rectangle([116.2621, 39.8412, 116.4849, 40.01236]);

  var task = ee.batch.Export.image.toCloudStorage({
    image: landsat,
    description: 'imageToCloudExample',
    bucket: 'tf-temp',
    fileNamePrefix: 'exampleExport',
    scale: 30,
    region: JSON.stringify( geometry.toGeoJSON()),
  });
    
  task.start(function () {
    console.log('Started task #' + task.id);
    }, function (error) {
      console.log('Error: ' + error);
    });

});

```

**Comment by donmccurdy** [comment]
Ok, great to hear it's working!
