### ISSUE TITLE
Initialize using a proxy server

### ISSUE THREAD

**Issue by sahutkarsh** [google/earthengine-api#64]
I am trying to initialize the ee module (in jupyter notebook) using a proxy server. It gives me the following error when i run ee.Initialize()

    TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not 
    properly respond after a period of time, or established connection failed because connected host has 
    failed to respond

I have tried setting the notebook environment with my proxy settings:

    import os
    os.environ['HTTP_PROXY'] = 'my_proxy_id:proxy_port'
    os.environ['HTTPS_PROXY'] = 'my_proxy_id:proxy_port'

It still won't connect to the server.

**Comment by CaptureOSM** [comment]
Does anyone have a solution for this issue? I have the same problem.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
