### ISSUE TITLE
DeprecationWarning on inspect.getargspec()

### ISSUE THREAD

**Issue by cgmorton** [google/earthengine-api#66]
I am using pytest to run tests that make Earth Engine calls.  During the tests the warning below is printed lots of times.  It doesn't seem like this is impacting anything (and I could easily hide or suppress them) so sorry in advance if this isn't a real issue.  I am running version 0.1.152 of the Python API on Python 3.6 in Windows.  I don't see this warning any other time though, so I'm not sure what it is about pytest that causes/shows it.

```
  C:\Miniconda3\envs\openet\lib\site-packages\ee\__init__.py:216: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
    args_count = len(inspect.getargspec(arg).args)
```

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
