### ISSUE TITLE
How can i upload assets in Jupyter?

### ISSUE THREAD

**Issue by parkdino** [google/earthengine-api#69]
Can i  realize it through gee_tools or any other ways?

**Comment by tylere** [comment]
From within a Jupyter notebook, you can use the Earth Engine Python API:

ee.data.startIngestion (for rasters)
https://github.com/google/earthengine-api/blob/master/python/ee/data.py#L754

ee.data.startTableIngestion (for tables)
https://github.com/google/earthengine-api/blob/master/python/ee/data.py#L811

You can also execute shell commands (%%bash), which allows you to used the [Earth Engine Command Line tool](https://developers.google.com/earth-engine/command_line#upload).

**Comment by parkdino** [comment]
> From within a Jupyter notebook, you can use the Earth Engine Python API:
> 
> ee.data.startIngestion (for rasters)
> https://github.com/google/earthengine-api/blob/master/python/ee/data.py#L754
> 
> ee.data.startTableIngestion (for tables)
> https://github.com/google/earthengine-api/blob/master/python/ee/data.py#L811
> 
> You can also execute shell commands (%%bash), which allows you to used the [Earth Engine Command Line tool](https://developers.google.com/earth-engine/command_line#upload).

Sorry, is it same from within Colaboratory?

**Comment by tylere** [comment]
Colab does not have Earth Engine installed by default, but you can install it by running the following in a code cell:

`!pip install earthengine-api`

and then authenticate using

`!earthengine authenticate`

**Comment by parkdino** [comment]
> Colab does not have Earth Engine installed by default, but you can install it by running the following in a code cell:
> 
> `!pip install earthengine-api`
> 
> and then authenticate using
> 
> `!earthengine authenticate`

So is Colab almost same as Jupyter notebook?

**Comment by parkdino** [comment]
> The classic Jupyter Notebook and new JupyterLab are web-based user interfaces (UI) that the Jupyter project maintain. Colab is a web-based user interface that Google maintains. They all implement the Jupyter project's open standards for interactive computing (notebook format, communication protocol, kernel). Each UI has a different set of features, and there are pros and cons to each, depending on your use case. For uploading assets to Earth Engine, any of the UIs will work.

Thank you very much.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
