### ISSUE TITLE
Can earth engine do this?

### ISSUE THREAD

**Issue by mikeacres** [google/earthengine-api#73]
Apologies if this isn't a suitable place for an enquiry like this...

I am searching for way to be able to obtain an image of earth (as a whole globe as if from space) from a particular date of my choosing and ideally centred around a location of my choice. The image only need be high resolution enough for printing purposes and does not require the ability to be 'zoomed in' at all. The key is that it be an image of earth from a particular date.

There is an application called zoom.earth which is the closest I have found however I cannot seem to extract the image it produces and it cannot be centred on a particular location.

Is earth engine able to produce this in some way or does anyone have any other suggestions. As i'm sure you are by now aware I am not involved in this area and am looking for assistance for a potential commercial enterprise.  

Any advice is greatly appreciated.

Michael
London, UK

**Comment by fitoprincipe** [comment]
Hi @mikeacres,

You should try Earth Engine and see if it is what you're looking for. You can register for free in https://signup.earthengine.google.com/, and visit https://developers.google.com/earth-engine/ for more information. If it suits you, then you could ask them the possibility of using it for commercial purposes. You can also read the Terms and Conditions in https://earthengine.google.com/terms/

Best
Rodrigo

**Comment by tylere** [comment]
Closing issue due to lack of follow up discussion.
