### ISSUE TITLE
Generate a random image from a normal distribution?

### ISSUE THREAD

**Issue by darkber1986** [google/earthengine-api#74]
Hi there, i would like to know if there is a way to generate a random image from a normal distribution instead of an uniform distribution? if not, can a normal distribution be implemented from an uniform distribution? thanks for your support, keep on the good work!

**Comment by mdhancher** [comment]
There's not a built-in function for that right now, so the easiest way to do it is probably via the [Box-Muller transform](https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform).

// Create two uniform random images (with different random seeds).
var u = ee.Image.random(0), v = ee.Image.random(1);
// Use the Box-Muller transform to generate a uniform random number.
var r = u.log().multiply(-2).sqrt().multiply(v.multiply(2*Math.PI).cos());

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
