### ISSUE TITLE
Have NDVI layer and want to calculate area according to threshold values in Python API of GEE

### ISSUE THREAD

**Issue by sohinigoswami** [google/earthengine-api#75]
**I am using this code : But it is giving the error- EEException: Invalid argument for ee.Reducer(): ({'geometry': [[74.022029, 20.103245], [74.022029, 20.116564], [74.038048, 20.116564], [74.038048, 20.103245]], 'reducer': <ee.Reducer object at 0x03D06FF0>, 'scale': 10},).  Must be a ComputedObject.**
ndvi = clip.normalizedDifference(['B8', 'B4'])
#NDVI=ndvi.multiply(100).uint8()
bad=ndvi.gte(0)and(ndvi.lte(0.2)).rename('bad')
avg=ndvi.gt(0.2) and(ndvi.lte(0.35)).rename('avg')
good=ndvi.gt(0.35)and(ndvi.lte(1)).rename('good')
ndvi.addBands(['bad', 'avg', 'good'])
print ndvi
areas = ndvi.select(['bad', 'avg', 'good']).multiply(ee.Image.pixelArea()).reduceRegion({'reducer':ee.Reducer.sum(),'geometry':geometry1,'scale':10});
print(areas)

**Comment by fitoprincipe** [comment]
Hi @sohinigoswami,

Your code is not reproducible, you haven't specify what `clip` and `geometry1` are. Anyhow, looking at ndvi bands, `clip` is a Sentinel 2 image. I made a test geometry and got the error. Your code has different issues, you'll spot them looking at the code that works:

``` python
ndvi = clip.normalizedDifference(['B8', 'B4'])
#NDVI=ndvi.multiply(100).uint8()
bad=ndvi.gte(0)and(ndvi.lte(0.2)).rename('bad')
avg=ndvi.gt(0.2) and(ndvi.lte(0.35)).rename('avg')
good=ndvi.gt(0.35)and(ndvi.lte(1)).rename('good')
ndvi = ndvi.addBands([bad, avg, good]) # arguments are images not strings
print(ndvi.getInfo()) # use getInfo() to print in python
areas = ndvi.select(['bad', 'avg', 'good']).multiply(ee.Image.pixelArea()).reduceRegion(reducer=ee.Reducer.sum(), geometry=geometry1, scale=10) # reduceRegion takes keyword arguments, not a dict
print(areas.getInfo())
```

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
