### ISSUE TITLE
Feature Request : Point1.heading(Point2)

### ISSUE THREAD

**Issue by ExploraSciences** [google/earthengine-api#78]
Hello, As part of my research on megalith alignments, I need to know, for very long distances, the heading of a point1 to a point2 with the same precision as that provided by Google Earth Pro (with the ruler) . Indeed, the algorithms of Karney or Vincenty are too far from reality in relation to my need. Would it be possible to create a function like Point1.heading (P2) which returns the same result as Google Earth Pro? I think there are many other cases where users might need this feature, at least me, I am blocked without this feature :)
(I'm sorry for the automatic translation)
thank you so much

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help

Not that this repo is for Google Earth Engine, not Google Earth.
