### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by stefanocudini** [google/earthengine-api#8]
In a short time it'll be possible to find this library, javascript side, distributed via npm?

**Comment by gena** [comment]
Try https://github.com/gena/ee-runner

`npm install ee-runner`

**Comment by donmccurdy** [comment]
We're now publishing an npm package, updated regularly: https://www.npmjs.com/package/@google/earthengine

Example:

```
npm install @google/earthengine
```

**Comment by stefanocudini** [comment]
@donmccurdy  good!
