### ISSUE TITLE
Feature request: fuzzy classification

### ISSUE THREAD

**Issue by samharrison16** [google/earthengine-api#81]
Fuzzy classification allows pixels or objects to belong to more than one class in a classification. I've searched around and can't seem to find a way of doing in on GEE. Fuzzy classifications are becoming more prevalent in remote sensing and would be a really useful addition in GEE.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
