### ISSUE TITLE
PIL error in fresh docker environment

### ISSUE THREAD

**Issue by David-Loibl** [google/earthengine-api#82]
Hi, 
I have installed a local docker environment (on Linux Mint) following the instructions at the [GEE developers page](https://developers.google.com/earth-engine/python_install-datalab-local) and successfully executed the scripts in the docs-earthengine directory.
However, when I try to execute some of the example scripts, e.g. for [images](https://github.com/google/earthengine-api/blob/645969797a997dc87591752b8b12d89b958b171f/python/examples/Image/landcover_cleanup.py) or [ImageCollections](https://github.com/google/earthengine-api/blob/645969797a997dc87591752b8b12d89b958b171f/python/examples/ImageCollection/filtered_composite.py), I get the PIL error that was [reported before](https://github.com/google/earthengine-api/issues/15):
`ERROR: A Python library (PIL) used by the Earth Engine API mapclient module
    was not found. Information on PIL can be found at:
    http://pypi.python.org/pypi/PIL`

It's the first time I work with docker. If I get the concept right, the idea is to provide a tailored environment that should/can not be modified. So even if it was possible, manually changing mapclient.py is probably not the right approach. Is this a configuration issue in the docker file or am I doing something wrong?

Best,
David

**Comment by tylere** [comment]
Hi David,

We are in the process of updating the Python installation instructions. In the meantime:
* if you want to install using Docker I would refer you to these community docs: https://github.com/gee-community/ee-jupyter-contrib/tree/master/docker/jupyter-scipy-notebook-ee
* if you want to install using conda, there is a package on conda-forge: https://github.com/conda-forge/earthengine-api-feedstock

Cheers,
Tyler

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
