### ISSUE TITLE
Bug with geojson handling

### ISSUE THREAD

**Issue by piizei** [google/earthengine-api#84]
There is a bug how geojsons are handled when reducing a region.

This is demonstrated on a script: 
https://code.earthengine.google.com/b8716ebf82b547932f043eeab980a720

when image collection is of small scale (Sentinel2) and geometry is geojson (ee.Geometry(geojson))  following fails:
ui.Chart.image.series(imageCollection, geometry, ee.Reducer.mean(), 250) 
when image collection is of higher scale (Modis) the same works.

when geometry is the same but constructed as ee.Geometry.Multipolygon (ee.Geometry.MultiPolygon(geojson.geometries[0].coordinates)) both Sentinel2 and Modis work.

Error with Geojson + Sentinel2 is 'user memory limit exceed'.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
