### ISSUE TITLE
Feature request:  Random Forest classifier

### ISSUE THREAD

**Issue by lholsinger** [google/earthengine-api#88]
I would like to request that a "maximum node" parameter be added to the ee.Classifier.randomForest() built-in function.  Specifically, it would be tremendously helpful to be able to specify the maximum number of terminal nodes trees that a forest can have.  Thanks for your consideration!

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
