### ISSUE TITLE
Database support

### ISSUE THREAD

**Issue by adamjstewart** [google/earthengine-api#91]
I would like to scale up my application to global scale, which involves more data that can fit into memory. During preprocessing, I would like to save a single pixel per field for each Landsat image worldwide. I would like to store this in a database so that I can access this later during training time. Since the data is too large to fit into memory, KML and SHP won't work. TFRecord could work, but I'm not using TensorFlow. Support for an RDBMS like MySQL would be much appreciated for storing tables.

**Comment by tylere** [comment]
Assuming you can represent your field boundaries as an Earth Engine Feature Collection, you can generate per-field attributes using [ee.Image.reduceRegions](https://developers.google.com/earth-engine/api_docs#ee.image.reduceregions) and export to a CSV file using [Export.table.toCloudStorage](https://developers.google.com/earth-engine/api_docs#export.table.tocloudstorage). The CSV can then be imported into a RDBMS.

I am going to close this issue, as we are in the process of transitioning to Google Issue Tracker. If you want to file a follow up feature request or bug report, please do so following the links on the [Get Help](https://developers.google.com/earth-engine/help) page of the Earth Engine docs.
