### ISSUE TITLE
Add object cross-references to parameters in the EE reference docs

### ISSUE THREAD

**Issue by AndrewAnnex** [google/earthengine-api#98]
It would be very helpful if a searchable sphinx docs / readthedocs was made for EE, the website/code editor isn't really sufficient and they don't display well in fire fox

**Comment by kpreid** [comment]
There is https://developers.google.com/earth-engine/api_docs which should contain the same info as in the Code Editor and be text searchable — does that provide what you want?

**Comment by AndrewAnnex** [comment]
hmm... actually that is helpful and mostly solves my issue. It would be nice if object cross-referencing was added (ie I could click on ee.ErrorMargin in a param for ee.Feature.bounds, and end up in the right spot on the page). thanks

**Comment by kpreid** [comment]
Thanks for the suggestion!

**Comment by jacksonwelsh** [comment]
Tagging along, is there a way to contribute to this documentation? I've noticed many of the components referenced in the documentation simply have a placeholder in the examples, especially on the Python side of things.

**Comment by tylere** [comment]
@jacksonwelsh Currently, there is not a way to contribute to the code examples shown in the API docs. Documentation contributions are currently limited to the [Community Tutorials](https://developers.google.com/earth-engine/tutorials/community/write), but we are planning to expanding where docs contributions can be accepted.

**Comment by AndrewAnnex** [comment]
@tylere I guess we should close this issue?

**Comment by tylere** [comment]
I created a feature request based on the object cross-referencing comment.
https://issuetracker.google.com/issues/176546490

Closing this issue, to encourage the use of [suggested way of requesting features](https://developers.google.com/earth-engine/help#feature_requests).
